wellcomecollection/platform-infrastructure

.gitignore
accounts/digirati.tf
accounts/terraform.tf

For https://github.com/wellcometrust/platform/issues/4200
Also a tiny bit of housekeeping.

Remove references to wc-assets-archivestorage

---

assets/s3_workingstorage.tf

Tentative fix for https://github.com/wellcomecollection/platform/issues/4370

Allow the digitisation team to download the MIRO archive

---

assets/s3_workingstorage.tf

Closes https://github.com/wellcomecollection/platform/issues/4371

Remove storage account access to wc-assets-workingstorage

---

shared/outputs.tf
shared/vpcs.tf

A safe(ish) network space to run infrastructure in that is for examples & experiments.

Developer VPC for experiments

---

dns/main.tf

Part of https://github.com/wellcomecollection/wellcomecollection.org/issues/4088

Redirect alpha site to respective github repo

---

digitisation_infra/provider.tf
digitisation_infra/s3_client_transfer.tf
digitisation_infra/s3_delivery_service.tf
digitisation_infra/s3_digitisation_av.tf
digitisation_infra/s3_digitisation_transfer.tf

For https://github.com/wellcomecollection/platform/issues/3793

Add Terraform tags to the digitisation infra resources

---

critical/back_end/secrets.tf

Required for https://github.com/wellcomecollection/wellcomecollection.org/pull/5310

Secrets for experience stack

---

.gitignore
accounts/account.tf
accounts/provider.tf
accounts/rolesets.tf

For https://github.com/wellcomecollection/platform/issues/4604

Provision role based access for digirati devs

---

critical/back_end/outputs.tf
critical/back_end/provider.tf
critical/back_end/secrets.tf
critical/back_end/vpcs.tf

For https://github.com/wellcomecollection/platform/issues/4605

Add VPC for iiif-services to be worked in by Digitati

---

dns/README.md
dns/main.tf
dns/modules/redirect/main.tf
dns/provider.tf

Part of wellcomecollection/platform#4621

Use the new DNS role in the DNS infra

---

accounts/modules/role_policies/ci/policies.tf
accounts/modules/role_policies/ci/variables.tf

Allow CI role to write to release table

Add release table permissions

---

accounts/modules/role_policies/ci/policies.tf

Needed to deploy from CI.
Part of https://github.com/wellcomecollection/platform/issues/3806

Add permissions to list and update ECS services

---

scripts/create_saved_logging_searches.py

We can re-run this script whenever to recreate our saved searches.
Closes https://github.com/wellcomecollection/platform/issues/4545

Add a script for creating saved searches in Kibana

---

dns/provider.tf

Just using the new account.
Applies cleanly.

use new routemaster account

---

cloudfront/main.tf
cloudfront/provider.tf
cloudfront/wellcomecollection/main.tf
cloudfront/wellcomecollection/variables.tf

Hold our CloudFront distributions in Terraform to have them documented, clear, reproducible.

Import Wellcome Collection API CloudFront distros

---

critical/back_end/modules/nat_instance/main.tf
critical/back_end/modules/public-private-igw/main.tf
critical/back_end/modules/public-private-igw/variables.tf
critical/back_end/vpcs.tf

For https://github.com/wellcomecollection/platform/issues/4774

Use a t3.large NAT instance for the storage service

---

critical/back_end/modules/nat_instance/main.tf
critical/back_end/modules/public-private-igw/main.tf
critical/back_end/modules/public-private-igw/variables.tf
critical/back_end/vpcs.tf

Reverts wellcomecollection/platform-infrastructure#50

Revert "Use a t3.large NAT instance for the storage service"

---

builds/terraform/data.tf
builds/terraform/locals.tf
builds/terraform/main.tf

For https://github.com/wellcomecollection/platform/issues/4717

Add Buildkite stack to Terraform

---

critical/back_end/outputs.tf
critical/back_end/terraform.tf

Another part of wellcomecollection/platform#4802
Relies on:

Don't re-export even more VPCs

---

.buildkite/pipeline.yml
.buildkite/scripts/commands.py
.buildkite/scripts/git_utils.py
.buildkite/scripts/provider.py
.buildkite/scripts/run_autoformat.py
Makefile
accounts/catalogue/locals.tf
docker_run.py
scripts/create_saved_logging_searches.py

This config is copied from the catalogue repo.
Closes https://github.com/wellcomecollection/platform/issues/4808

Add autoformatting in Buildkite

---

critical/back_end/secrets.tf
scripts/create_saved_logging_searches.py

In order to update Archivematica infra.
For https://github.com/wellcomecollection/platform/issues/4794
**This terraform has been applied.**

Copy logging secrets to Workflow account

---

assets/s3_workingstorage.tf

Part of https://github.com/wellcomecollection/platform/issues/4809

Allow storage account to read and get from working storage

---

accounts/identity/account.tf
accounts/identity/locals.tf
accounts/identity/outputs.tf
accounts/identity/provider.tf
accounts/identity/terraform.tf
accounts/identity/vpcs.tf
accounts/platform/rolesets.tf
accounts/platform/terraform.tf
dns/locals.tf
dns/main.tf
dns/terraform.tf

Add Identity account infra

---

accounts/platform/outputs.tf
builds/terraform/buildkite.tf

Needed for builds on https://github.com/wellcomecollection/identity

Ensure Buildkite can assume identity CI role

---

accounts/identity/.terraform.lock.hcl
critical/back_end/.terraform.lock.hcl
images/terraform/.terraform.lock.hcl

Adds missing terraform lockfiles

---

cloudfront/productboard/main.tf

This change ensures that they're in sync.

Productboard CloudFront distro has drifted from what is deployed

---

assets/.terraform.lock.hcl
assets/provider.tf
assets/s3_workingstorage.tf

See https://wellcome.slack.com/archives/CN56BRQ5B/p1611053093020900

Give the digitisation team access to the Proquest backups

---

accounts/modules/account/federated/outputs.tf
accounts/modules/assumable_role/aws/variables.tf
accounts/modules/assumable_role/federated/outputs.tf
accounts/modules/users/list_roles_user/outputs.tf
images/publish_mirrored_images.py
images/terraform/ecr.tf

Provision the images we mirror from Docker hub in Terraform, update the mirroring script accordingly.
Note: This terraform is applied.

Provision mirrored images

---

images/publish_mirrored_images.py
images/terraform/ecr.tf

Mirror wellcome/tox image

---

cloudfront/modules/certificate/main.tf
cloudfront/wellcomelibrary.org/terraform/.terraform.lock.hcl
cloudfront/wellcomelibrary.org/terraform/cert.tf
cloudfront/wellcomelibrary.org/terraform/cf_behaviours.tf
cloudfront/wellcomelibrary.org/terraform/cf_origins.tf
cloudfront/wellcomelibrary.org/terraform/cloudfront_distro/main.tf
cloudfront/wellcomelibrary.org/terraform/cloudfront_distro/variables.tf
cloudfront/wellcomelibrary.org/terraform/main.tf
cloudfront/wellcomelibrary.org/terraform/provider.tf
cloudfront/wellcomelibrary.org/terraform/terraform.tf

Adds a skeleton CloudFront distribution for wellcomelibrary.org.
Part of https://github.com/wellcomecollection/platform/issues/4977
**Note:** This change has been applied.

Add wellcomelibrary.org CloudFront distribution

---

cloudfront/iiif.wellcomecollection.org/terraform/cf_behaviours.tf
cloudfront/iiif.wellcomecollection.org/terraform/cf_origins.tf
cloudfront/iiif.wellcomecollection.org/terraform/origin_sets/origin_set.tf

It was a little difficult to see what was going on with the origins here, so i've rearranged things a bit and removed the now unused Loris references.

Clean up origins in iiif CloudFront distro

---

cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.test.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.ts
cloudfront/wellcomelibrary.org/terraform/cf_behaviours.tf
cloudfront/wellcomelibrary.org/terraform/locals.tf

Part of https://github.com/wellcomecollection/platform/issues/5080

Redirect events URLs from wellcomelibrary.org

---

cloudfront/wellcomelibrary.org/edge-lambda/generateStaticRedirects.ts
cloudfront/wellcomelibrary.org/edge-lambda/package.json
cloudfront/wellcomelibrary.org/terraform/cf_behaviours.tf
cloudfront/wellcomelibrary.org/terraform/locals.tf

Rolls out the static redirects to prod.

Static redirects in prod

---

cloudfront/wellcomelibrary.org/edge-lambda/generateStaticRedirects.ts
cloudfront/wellcomelibrary.org/edge-lambda/package.json
cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryBlogRedirect.test.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryBlogRedirect.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.ts
cloudfront/wellcomelibrary.org/edge-lambda/testRedirects.ts
cloudfront/wellcomelibrary.org/edge-lambda/yarn.lock
cloudfront/wellcomelibrary.org/terraform/blog.tf
cloudfront/wellcomelibrary.org/terraform/cloudfront_distro/variables.tf
cloudfront/wellcomelibrary.org/terraform/lambdas.tf
cloudfront/wellcomelibrary.org/terraform/locals.tf
cloudfront/wellcomelibrary.org/terraform/main.tf
cloudfront/wellcomelibrary.org/terraform/outputs.tf

https://blog.stage.wellcomelibrary.org
TODO:
In a future PR:
- Update internal DNS for blog.stage.wellcomelibrary.org (requested REQ0021077)
- Confirm final crawl and set the correct URL prefix in the lambda.
- Deploy updated lambda to prod & point blog.wellcomelibrary.org -> at CloudFront
- Update internal DNS for blog.wellcomelibrary.org

Redirect blog.wellcomelibrary.org to Internet Archive

---

cloudfront/iiif.wellcomecollection.org/tests/README.md

To make it a bit easier to run these.

Add a README.md for running iiif CF tests

---

cloudfront/wellcomelibrary.org/edge-lambda/src/lookupRedirect.test.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/redirectHelpers.test.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/redirectHelpers.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/redirectToRoot.test.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/redirectToRoot.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/testEventRequest.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/testHelpers.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryPassthru.test.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.test.ts
cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.ts
cloudfront/wellcomelibrary.org/terraform/blog.tf
cloudfront/wellcomelibrary.org/terraform/cloudfront_distro/main.tf
cloudfront/wellcomelibrary.org/terraform/cloudfront_distro/variables.tf
cloudfront/wellcomelibrary.org/terraform/locals.tf
cloudfront/wellcomelibrary.org/terraform/main.tf

For https://github.com/wellcomecollection/platform/issues/5086

HTTP to HTTPS redirect with CORS headers

---

.github/pull_request_template.md

To help make sure what we _think_ we're changing is what we are changing.

Add pull_request_template

---

accounts/workflow/iam_workflow_support.tf

Give the workflow-support role permission to use CloudShell

---

accounts/experience/iam_experience_ci.tf
cloudfront/wellcomelibrary.org/terraform/cf_behaviours.tf
cloudfront/wellcomelibrary.org/terraform/cf_origins.tf

Ref https://github.com/wellcomecollection/platform/issues/5114
* add the MoH origin with relevant path patterns to stage
* remove non-user API/item behaviours
Will show when we do the prod version

Moh cloudfront

---

accounts/digitisation/s3_delivery_service.tf
accounts/workflow/iam_workflow_support.tf
assets/s3_workingstorage.tf

This is already applied and tested as working.

Allow workflow-support to copy objects from s3://assets-workingstorage/av/

---

cloudfront/wellcomelibrary.org/edge-lambda/tsconfig.json

https://github.com/microsoft/TypeScript/blob/main/src/compiler/diagnosticMessages.json#L4170-L4173

appease TS6059

---

accounts/platform/iam_platform_ci.tf

For https://github.com/wellcomecollection/catalogue-api/issues/103
This is already applied.

Allow publishing the source model library in CI

---

monitoring/terraform/.terraform.lock.hcl
monitoring/terraform/locals.tf
monitoring/terraform/main.tf
monitoring/terraform/provider.tf
monitoring/terraform/stack/post_to_slack.tf
monitoring/terraform/stack/variables.tf
monitoring/terraform/terraform.tf

This just gets the stack planning again, no changes.

Get the monitoring stack planning with the latest version of TF

---

critical/outputs.tf
critical/topics.tf
monitoring/dlq_to_slack_alerts/src/dlq_to_slack_alerts.py
monitoring/terraform/.terraform.lock.hcl
monitoring/terraform/dlq_to_slack_alerts.tf
monitoring/terraform/modules/dlq_to_slack_alerts/iam.tf
monitoring/terraform/modules/dlq_to_slack_alerts/lambda.tf
monitoring/terraform/modules/dlq_to_slack_alerts/secrets.tf
monitoring/terraform/modules/dlq_to_slack_alerts/topics.tf
monitoring/terraform/modules/dlq_to_slack_alerts/variables.tf
monitoring/terraform/provider.tf
monitoring/terraform/stack/grafana/main.tf
monitoring/terraform/stack/grafana/service/iam_role/README.md
monitoring/terraform/stack/grafana/service/iam_role/main.tf
monitoring/terraform/stack/grafana/service/iam_role/outputs.tf
monitoring/terraform/stack/grafana/service/iam_role/variables.tf
monitoring/terraform/stack/grafana/service/main.tf
monitoring/terraform/stack/grafana/service/outputs.tf
monitoring/terraform/stack/grafana/service/service.tf
monitoring/terraform/stack/grafana/service/variables.tf

For https://github.com/wellcomecollection/platform/issues/5245
* Add default tags everywhere
* Make sure the Lambda is working in the platform account
* Use a per-account name for the SNS topic and Lambda so it's easier to debug

Further Terraform fixes for the SQS DLQ alerting Lambda

---

monitoring/terraform/modules/slack_alert_on_cloudfront_errors/main.tf

Display float error percentages at a fixed precision

---

costs_report/costs_report/costs_report.py
costs_report/terraform/cloudwatch.tf

Move it forward by an hour to run at 9am in BST, and add a few more comments.

Tweak the costs reporter (again)

---

assets/s3_workingstorage.tf

Allow Harkiran and Ashley to upload files into the "av" prefix.
```
~ resource "aws_s3_bucket_policy" "working_storage" {
id     = "wellcomecollection-assets-workingstorage"
~ {
~ {
~ Principal = {
~ AWS = [
- "arn:aws:iam::299497370133:root",
- "arn:aws:iam::404315009621:root",
"arn:aws:iam::975596993436:root",
+ "arn:aws:iam::404315009621:root",
+ "arn:aws:iam::299497370133:root",
]
}
},
~ {
~ Principal = {
~ AWS = [
- "arn:aws:iam::299497370133:root",
- "arn:aws:iam::404315009621:root",
"arn:aws:iam::975596993436:root",
+ "arn:aws:iam::404315009621:root",
+ "arn:aws:iam::299497370133:root",
]
}
},
+ {
+ Action    = "s3:Put*"
+ Effect    = "Allow"
+ Principal = {
+ AWS = "arn:aws:iam::404315009621:root" …
```

Allow the digitisation team to upload into the av/ prefix

---

builds/terraform/buildkite.tf

A leftover tentative fix for https://github.com/wellcomecollection/platform/issues/5364

Disable Docker user namespace mapping

---

images/nginx/frontend.nginx.conf
images/nginx/template.Dockerfile

See comment for the reason behind this, I've verified locally that it works

Increase proxy buffer size for frontend nginx

---

costs_report/costs_report/costs_report.py
costs_report/terraform/iam.tf
costs_report/terraform/rolesets.tf

Closes https://github.com/wellcomecollection/platform/issues/5386

Add the microsites account to our costs report

---

monitoring/slack_alerts/metric_to_slack_alert/src/metric_to_slack_alert.py

https://github.com/wellcomecollection/platform-infrastructure/pull/286 didn't quite work, I saw a delay of ~90s so hopefully this will cover it.

Move the logging window again

---

monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
monitoring/slack_alerts/ecs_tasks_cant_start_alert/src/ecs_tasks_cant_start_alert.py
monitoring/slack_alerts/lambda_errors_to_slack_alerts/src/lambda_errors_to_slack_alerts.py
monitoring/slack_alerts/metric_to_slack_alert/src/metric_to_slack_alert.py

As per @paul-butcher's suggestion in https://github.com/wellcomecollection/platform-infrastructure/pull/288#discussion_r829268806

Improved HTTP error handling in all the alerting lambdas

---

monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py

Fix key name in auth0 alerting Lambda

---

accounts/catalogue/iam_catalogue_ci.tf
accounts/modules/vpc/provider.tf

For https://github.com/wellcomecollection/platform/issues/5430

Update permissions for the internal model tool + sans-CCR

---

accounts/catalogue/iam_catalogue_ci.tf

Reverts wellcomecollection/platform-infrastructure#295

Revert "Change ci permissions"

---

monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py

We don't need to know about these

Stop alerting on "Warnings during login"

---

.buildkite/scripts/run_autoformat.sh

For wellcomecollection/platform#5545, which includes a discussion of the benefits.

Use the Terraform image from ECR Public

---

cloudfront/modules/redirect/main.tf
cloudfront/modules/redirect/provider.tf
cloudfront/wellcomecollection.org/terraform/.terraform.lock.hcl

For https://github.com/wellcomecollection/platform/issues/5557

Remove the deprecated template provider from the CloudFront config

---

cloudfront/modules/redirect/main.tf
cloudfront/modules/redirect/provider.tf
cloudfront/wellcomecollection.org/terraform/.terraform.lock.hcl

For https://github.com/wellcomecollection/platform/issues/5557. This is a no-op plan.

Remove another use of the deprecated template provider

---

monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py

This should be a no-op change.

Make the Auth0 alert Lambda a bit more readable/simpler

---

critical/elastic_logging_cluster.tf

This reflects reality - tf change is a no-op

Upgrade logging cluster to 8.4.0

---

critical/elastic_logging_cluster.tf

This matches @alexwlchan's changes in the console and is a good idea regardless

Bump APM node size

---

monitoring/slack_alerts/metric_to_slack_alert/src/metric_to_slack_alert.py

These shouldn't have been f-strings

Fix alerting Lambda

---

monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
monitoring/terraform/.terraform.lock.hcl
monitoring/terraform/s3.tf

We don't need to worry about someone getting rate limited on login

---

accounts/README.md
accounts/platform/locals.tf
accounts/platform/rolesets.tf
accounts/platform/terraform.tf
accounts/systems_strategy/.terraform.lock.hcl
accounts/systems_strategy/account.tf
accounts/systems_strategy/locals.tf
accounts/systems_strategy/outputs.tf
accounts/systems_strategy/provider.tf
accounts/systems_strategy/terraform.tf

For https://github.com/wellcomecollection/platform/issues/5655

Add the Systems Strategy account to our default roleset

---

cloudfront/wellcomecollection.org/terraform/main.tf

For https://github.com/wellcomecollection/platform/issues/5692

Add the domain validation record for D&T

---

images/publish_mirrored_images.py
images/terraform/ecr.tf

For https://github.com/wellcomecollection/platform/issues/5724

Mirror the official Black Docker images into our ECR account

---

critical/.terraform.lock.hcl
critical/elastic_reporting_cluster.tf

Bump reporting cluster version to match reality

---

cloudfront/iiif.wellcomecollection.org/terraform/.terraform.lock.hcl
cloudfront/iiif.wellcomecollection.org/terraform/lambda_dlcs_path_rewrite.tf

Bump DLCS path rewrite lambda to Node 16

---

cloudfront/wellcomecollection.org/terraform/.terraform.lock.hcl
cloudfront/wellcomecollection.org/terraform/main.tf

See https://github.com/wellcomecollection/platform/issues/5748
> [!NOTE]
> This change has been applied.

Add a TXT validation record for certificate renewal

---

monitoring/slack_alerts/metric_to_slack_alert/src/metric_to_slack_alert.py

https://github.com/wellcomecollection/platform/issues/5777
Remove unnecessary if statement covering catalogue pipeline DLQ alerts as the corresponding alarms will be removed.
Depends on https://github.com/wellcomecollection/catalogue-pipeline/pull/2700 and https://github.com/wellcomecollection/terraform-aws-sqs/pull/11
```
id                             = "catalogue_api_gateway_to_slack_alerts"
~ last_modified                  = "2023-03-07T09:10:05.000+0000" -> (known after apply)
~ source_code_hash               = "HLxzXCamKv1Z3Fa63U+p+nDCBb4JNRa85kiZGHL+D1k=" -> "7FD2tKg/AcxOg+TOgw6nKH9/oX3I0Ms/P1O002ucoXE="
}
~ resource "aws_lambda_function" …
```

Remove catalogue dlq alerts from slack

---

cloudfront/invalidation/lambda/deploy.js

Fix `Region is missing` error in BK by passing the region from env var
Run bk pipeline deploy step
bk pipeline deploy step successful

fix error region is missing

---

cloudfront/invalidation/lambda/deploy.js

use string

---

cloudfront/invalidation/lambda/deploy.js

add optional clientConfig
