- critical/api.wellcomecollection.org/cloudfront.tf
- critical/cognito.tf
- critical/config.tf
- critical/iam.tf
- critical/locals.tf
- critical/main.tf
- critical/outputs.tf
- critical/provider.tf
- modules/elasticcloud/main.tf
- modules/elasticcloud/outputs.tf
- modules/elasticcloud/variables.tf
This gets the stack to plan cleanly with 0.12 (no deprecation warnings or errors).
I haven't applied this because it wants to change the DDS Cognito user pool, and I'm not sure why (or how the existing Terraform could ever have done this):
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
~ resource "aws_cognito_user_pool_client" "dds" {
allowed_oauth_flows                  = [
"client_credentials",
]
allowed_oauth_flows_user_pool_client = true
~ allowed_oauth_scopes                 = [
- "https://api-stage.wellcomecollection.org/storage/v1/bags",
- "https://api-stage.wellcomecollection.org/storage/v1/ingests", …
```
> Bump the critical stack to terraform0.12

- shared/vpcs.tf
The experience AWS account is using the default VPC which is [not recommended](https://lmgtfy.com/?q=aws+why+not+use+default+vpc).
> Add a non-default VPC for the experience account

- accounts/iam_roles.tf
We want users with the workflow-support role to be able to move objects around S3 using the "Actions > Move" menu in the S3 Console, for example to move an object out of `failed/`.
This means they need:
* To be able to list every bucket in the account (the "Move" menu shows you a list of buckets so you can choose a move target)
* Give all the Get/Put permissions; apparently GetObject and PutObject alone aren't quite enough.
This is already applied; I was debugging it with Ashley just now.
> Allow workflow-support users to move objects within the bucket

- accounts/iam_roles.tf
- digitisation_infra/locals.tf
- digitisation_infra/provider.tf
- digitisation_infra/s3_client_transfer.tf
- digitisation_infra/s3_delivery_service.tf
- digitisation_infra/s3_digitisation_av.tf
- digitisation_infra/s3_digitisation_transfer.tf
- digitisation_infra/terraform.tf
As far as I can tell, these buckets were being managed by hand. Boo!
This adds:
* Terraform definitions for the existing buckets
* Read permissions for workflow users to get to certain buckets (in particular Harkiran and the A/V buckets)
Closes https://github.com/wellcomecollection/platform/issues/4401
> Manage the digitisation S3 buckets in Terraform

- containers/fluentbit/extra.conf
This wasn't caught when setting up the logging because we didn't have an index template.
The index templates require that the document type is `_doc` – if it’s possible to change that, it's very well hidden. Easier to lean into the ES way of doing things, and ditch the custom document type.
This change is published and running in the storage staging.
> Add an explicit document type for the fluentbit container

- accounts/rolesets.tf
Hosted zone records for wellcomecollection.org are moving to a new account, access to that new account is provisioned here.
Applied and tested.
Part of https://github.com/wellcometrust/wellcome-dns-infra/pull/120
> Adds new Route53 management role

- assets/iam_users.tf
- assets/provider.tf
- assets/s3_workingstorage.tf
- assets/terraform.tf
I've sent the access/secret key pair to the cataloguers to set up as a site in FileZilla Pro.
Closes https://github.com/wellcomecollection/platform/issues/4567
> Add an IAM users for accessing MIRO images

- accounts/account.tf
- accounts/modules/account/aws/main.tf
- accounts/modules/account/aws/outputs.tf
- accounts/modules/account/aws/variables.tf
- accounts/modules/role_policies/ci/main.tf
- accounts/modules/role_policies/ci/policies.tf
- accounts/modules/role_policies/ci/variables.tf
- accounts/outputs.tf
- accounts/rolesets.tf
- builds/terraform/locals.tf
- builds/terraform/main.tf
- builds/terraform/platform/variables.tf
- builds/terraform/scala_library/iam_policy_document.tf
- builds/terraform/scala_library/variables.tf
- builds/terraform/terraform.tf
Instead of a fixed identity, CI should assume role allowing developers to mimic exactly the permissions and process of CI with regard to AWS permissions.
> CI for each repo should assume role

- accounts/modules/role_policies/ci/policies.tf
Ci role needs to be able to read SSM params.
> CI can get params

- accounts/iam_workflow_support.tf
This will allow them to reingest items from the storage service through Goobi without downloading and reuploading the files.
Closes https://github.com/wellcomecollection/platform/issues/4665
> Allow workflow-support users to read from the storage-service

- accounts/account.tf
- accounts/terraform.tf
Allows users within an account to assume roles created in accounts (will allow CI users to assume in same account roles).
> Add own account as principal for assumed roles

- cloudfront/iiif/main.tf
- cloudfront/iiif/variables.tf
- cloudfront/main.tf
- cloudfront/provider.tf
- cloudfront/terraform.tf
For https://github.com/wellcomecollection/platform/issues/4603
When this is released the following Loris specific CloudFront distro can be removed (along with the cert it uses, and that cert can then be definitively referenced in terraform here).
https://github.com/wellcomecollection/loris-infrastructure/blob/master/terraform/cloudfront.tf
> Add CloudFront distros for IIIF APIs

- critical/back_end/outputs.tf
Unfortunately couldn't test this locally with `terraform plan` due to perms.
> Add digirati_cidr_block_private output to critical backend

- cloudfront/iiif/main.tf
> Add a path for Loris URLs prefixed with s3:

- dns/main.tf
Making it more official. 
alpha is now managed via the wl.org hosted zone, which is with D&T for now.
> add rank. and remove alpha.

- builds/terraform/locals.tf
- builds/terraform/terraform.tf
- critical/back_end/outputs.tf
- critical/back_end/terraform.tf
- monitoring/terraform/locals.tf
- monitoring/terraform/terraform.tf
Another part of https://github.com/wellcomecollection/platform/issues/4802
I set up the `critical/back_end` stack to re-export any VPC outputs it already had, to avoid breaking any other Terraform stacks, but it would be better if consumers loaded the VPC info directly from `accounts/<name>`.
(Among other things, it means they'll always get the latest value. If you get it from `critical/back_end`, it might be stale if somebody has changed things in `accounts/<name>` but not re-applied in `critical/back_end`.)
This patch updates the configurations in platform-infrastructure to use the new Terraform state.
> Don't re-export VPCs through critical/back_end

- critical/back_end/outputs.tf
- critical/back_end/terraform.tf
Part of wellcomecollection/platform#4802
Relies on https://github.com/wellcomecollection/storage-service/pull/749
> Don't re-export the storage VPCs through the critical/back_end stack

- critical/back_end/outputs.tf
- critical/back_end/terraform.tf
Part of https://github.com/wellcomecollection/platform/issues/4802
Waiting for https://github.com/wellcomecollection/catalogue/pull/893
> Remove the last of the re-exported VPCs from the critical/back_end stack

- critical/back_end/cloudwatch_event_rules.tf
I _thought_ I'd done this already, but apparently not.
> Remove a CloudWatch event rule that isn't used anywhere

- scripts/migrations/2020-10-cleanup_parameter_store.py
- scripts/migrations/2020-10-deleted_parameters.json
For https://github.com/wellcomecollection/platform/issues/4846
We still have some services not using weco-deploy (Loris, bits of Archivematica, the stacks service), but this clears out a lot of them. Already run and results recorded; PR just for visibility.
> Add a script for cleaning up unused Parameter Store entries

- scripts/migrations/.gitignore
- scripts/migrations/2020-10-clear_millisecond_precision_locks.py
Dunno if we'll need this again, but might as well keep it around.
I've already run it against the versioner lock tables.
> Add a script for removing old DynamoDB locks

- accounts/identity/iam_identity_ci.tf
This is needed so the deployment scripts in buildkite are able to
execute the following steps:
- Create a new version of Lambda Function from S3 reference
- Create a Lambda alias to the new version
- Fetch all resources in the API gateway
- Update their integrations with the new Lambda.
- Update the API gateway authorizer to point to the new lambda.
- Create a new API gateway deployment.
> Allow identity-ci to manage Lambdas and API gateways

- dns/locals.tf
- dns/main.tf
Verifies SES as capable of using `wellcomecollection.org` to send e-mail. 
See https://en.wikipedia.org/wiki/DomainKeys_Identified_Mail to understand what's going on with the DKIM records!
> Adds SES verification and DKIM records for Identity project

- dns/locals.tf
- dns/main.tf
We'll use `account.wellcomecollection.org` rather than `identity.wellcomecollection.org`.
This PR adds the NS records for `accounts`.
Note: This change is applied.
> Add NS records for account.wellcomecollection.org

- accounts/identity/iam_identity_ci.tf
The deployment process via Buildkite requires the ability to modify AWS Lambda Function's and API Gateway resources. The permissions for this are already in place, but the ARN targets are invalid. This PR uses the correct ARN's.
> Refining permissions for API Gateway and Lambda Function deployments for Identity

- accounts/identity/iam_identity_ci.tf
The current ARN for the API Gateway IAM permissions for the Identity CI user target the `/stages` resources only. This is incorrect, wider scope is required. This change widens that scope to all API Gateway resources.
> Rescoping API Gateway permissions for Identity CI user

- accounts/identity/iam_identity_ci.tf
In order to complete the Buildkite deployment pipeline, the Identity CI user must be able to determine if a Lambda alias already exists.
> Adding Lambda 'GetAlias' to Identity CI

- accounts/identity/iam_identity_ci.tf
Required to allow the CI / CD process to determine if the respective IAM policy already exists.
> Adding 'lambda:GetPolicy' permission to 'identity-ci' IAM user

- cloudfront/.gitignore
- cloudfront/.terraform.lock.hcl
- cloudfront/edge-lambda/dlcs_path_rewrite.js
- cloudfront/iiif/main.tf
- cloudfront/iiif/variables.tf
- cloudfront/lambdas.tf
- cloudfront/locals.tf
- cloudfront/main.tf
- cloudfront/outputs.tf
- cloudfront/provider.tf
This change will redirect a set of Miro images in the staging environment to the new DLCS space where images are being registered as part of the miro migration work.
This PR intends to demonstrate a practical approach in code for moving staging/prod over from Loris to DLCS in a piecemeal fashion in order to ensure that this approach is viable and that all images are available. 
TODO:
Part of https://github.com/wellcomecollection/platform/issues/4883
> Adds lambda@edge redirects for Loris -> DLCS change

- cloudfront/api.wc.org/cert.tf
- cloudfront/api.wc.org/data.tf
- cloudfront/api.wc.org/main.tf
- cloudfront/api.wc.org/provider.tf
- cloudfront/iiif.wc.org/terraform/cert.tf
- cloudfront/iiif.wc.org/terraform/data.tf
- cloudfront/iiif.wc.org/terraform/main.tf
- cloudfront/iiif.wc.org/terraform/provider.tf
- cloudfront/logging.wc.org/cert.tf
- cloudfront/logging.wc.org/data.tf
- cloudfront/logging.wc.org/main.tf
- cloudfront/logging.wc.org/provider.tf
- cloudfront/modules/certificate/main.tf
- cloudfront/modules/certificate/outputs.tf
- cloudfront/modules/certificate/provider.tf
- cloudfront/modules/certificate/variables.tf
- cloudfront/reporting.wc.org/cert.tf
- cloudfront/reporting.wc.org/data.tf
- cloudfront/reporting.wc.org/main.tf
- cloudfront/reporting.wc.org/provider.tf
- cloudfront/roadmap.wc.org/cert.tf
- cloudfront/roadmap.wc.org/data.tf
- cloudfront/roadmap.wc.org/main.tf
- cloudfront/roadmap.wc.org/provider.tf
Follows #102
We used to create ACM certificates and the associated DNS validation records in the console, because we didn't have access to the right roles in the DNS account to manage them programatically. That's no longer the case; this module moves the certificates used by our CloudFront distributions to be managed by Terraform.
I didn't do monitoring.wc.org or auth.wc.org because the stacks that use those certificates have fallen quite far behind, and need a bit of work before we can plan/apply in them with current versions of Terraform.
> Manage our ACM certificates in Terraform

- critical/back_end/s3_platform_infra.tf
We shouldn't be keeping everything that goes in this bucket indefinitely. This is particularly driven by https://github.com/wellcomecollection/platform/issues/5025, which will start adding 1GB+ snapshots of the Sierra data to this bucket, and we don't need to keep multiple copies of that.
Because this is a potentially destructive change, I'm not going to apply it until it's reviewed.
> Add some lifecycle rules to the platform-infra bucket

- accounts/workflow/iam_workflow_support.tf
- assets/iam_users.tf
For https://github.com/wellcomecollection/platform/issues/5077
> Add permission to get to the Miro bucket for cataloguers_wellcome_images and workflow-support

- cloudfront/iiif.wellcomecollection.org/edge-lambda/src/dlcs_path_rewrite.test.ts
- cloudfront/iiif.wellcomecollection.org/edge-lambda/src/dlcs_path_rewrite.ts
- cloudfront/iiif.wellcomecollection.org/terraform/cf_behaviours.tf
- cloudfront/iiif.wellcomecollection.org/terraform/cf_origins.tf
- cloudfront/iiif.wellcomecollection.org/terraform/locals.tf
auth, file, pdf + thumbs paths need to use Lambda to remove the initial matching segment from path. Introduced new origin for auth.
To simplify `/thumbs/` paths we are renaming the dds to `/thumb/` and keeping dlcs as `/thumbs/`.
Removed cookies from `thumbs` as they are not required.
> Update dlcs auth, file, pdf + thumbs paths to use lambda

- cloudfront/iiif.wellcomecollection.org/terraform/cf_behaviours.tf
- cloudfront/iiif.wellcomecollection.org/terraform/cf_origins.tf
- cloudfront/iiif.wellcomecollection.org/terraform/cloudfront_distro/main.tf
- cloudfront/iiif.wellcomecollection.org/terraform/cloudfront_distro/variables.tf
- cloudfront/iiif.wellcomecollection.org/terraform/origin_sets/origin_set.tf
> I can't plan this locally so syntax could be wrong!
Added `forward_host` variable to origin_set. If this is true then `x-forwarded-host` is added to origin custom headers, set to value of alias for distro. Added to `/thumbs/` requests only for now, this will allow me to validate it works without affecting anything called by external code.
Applying this should update the 3 "dlcs_thumbs" origins in the 3 iiif.wc.org distros.
Tested setting this in a test CF distro with and without going via an Origin request lambda and the value is persisted.
> Add x-forwarded-host to specified origins

- accounts/modules/interface_endpoint/main.tf
- builds/terraform/buildkite.tf
- builds/terraform/security_group.tf
- builds/terraform/vpc.tf
We spent ~$250/mo in NAT Gateway costs for CI; see [Cost Explorer](https://console.aws.amazon.com/cost-management/home?#/custom?excludeRIRecurringCharges=false&startDate=2021-02-20&excludeTax=false&excludeSupportCharges=false&endDate=2021-03-22&timeRangeOption=Custom&hasAmortized=false&excludeRIUpfrontFees=false&filter=%5B%7B%22dimension%22:%22Operation%22,%22values%22:%5B%22NatGateway%22%5D,%22include%22:true,%22children%22:null%7D%5D&isTemplate=true&groupBy=TagKeyValue:Name&forecastTimeRangeOption=None&excludeCredit=false&excludeTaggedResources=false&reportType=CostUsage&chartStyle=Line&granularity=Daily&excludeOtherSubscriptionCosts=false&hasBlended=false&excludeRefund=false&reportName=Daily%20API%20operation%20costs&excludeDiscounts=true&usageAs=usageQuantity&excludeCategorizedResource …
> Use VPC endpoints to talk to ECR in CI

- cloudfront/iiif.wellcomecollection.org/terraform/cf_behaviours.tf
`Bearer` token used for authorization to restricted or "clickthrough" images.
Couldn't easily add tests for these as it's not a simple request/response, instead the viewer uses cookies + JS redirects to get token.
> Add authorization header to iiif /images requests

- accounts/catalogue/.terraform.lock.hcl
- accounts/data/.terraform.lock.hcl
- accounts/digirati/.terraform.lock.hcl
- accounts/digitisation/.terraform.lock.hcl
- accounts/experience/.terraform.lock.hcl
- accounts/identity/.terraform.lock.hcl
- accounts/modules/role_policies/ci/policies.tf
- accounts/platform/.terraform.lock.hcl
- accounts/reporting/.terraform.lock.hcl
- accounts/storage/.terraform.lock.hcl
- accounts/workflow/.terraform.lock.hcl
- cloudfront/wellcomelibrary.org/terraform/main.tf
A first step towards https://github.com/wellcomecollection/platform/issues/4910
I'm testing this with a modified version of weco-deploy that pushes to an ECR Public repository for the METS adapter.
> Add permissions for our CI users to push to ECR Public

- cloudfront/iiif.wellcomecollection.org/tests/rewrite_tests.py
This started failing (https://buildkite.com/wellcomecollection/platform-infrastructure-redirects/builds?branch=master&page=7), and i'm not sure why - this change recurses through "service"s in the returned JSON. 
It does look like the results of the API have changed though. e.g.
Previous:
```
Checking: https://iiif-test.wellcomecollection.org/image/b19582183_RAMC_391_4_0001.jp2/info.json
--
  | Found 'https://iiif-test.wellcomecollection.org/image/b19582183_RAMC_391_4_0001.jp2'
  | Found 'https://iiif-test.wellcomecollection.org/auth/clickthrough'
  | Found 'https://iiif-test.wellcomecollection.org/auth/clickthrough/logout'
  | Found 'https://iiif-test.wellcomecollection.org/auth/token'
  | Found 'https://iiif-test.wellcomecollection.org/auth/login'
  | Found …
```
> Recurse through @id containing elements

- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryArchiveRedirect.ts
- cloudfront/wellcomelibrary.org/terraform/blog.tf
- cloudfront/wellcomelibrary.org/terraform/cf_origins.tf
- cloudfront/wellcomelibrary.org/terraform/cloudfront_distro/main.tf
- cloudfront/wellcomelibrary.org/terraform/cloudfront_distro/variables.tf
- cloudfront/wellcomelibrary.org/terraform/dserve.tf
- cloudfront/wellcomelibrary.org/terraform/lambdas.tf
- cloudfront/wellcomelibrary.org/terraform/locals.tf
- cloudfront/wellcomelibrary.org/terraform/opac.tf
Manage DServe DNS (archives.wellcomelibrary.org) in terraform. 
This PR adds DNS records / stage cloudfront distro to be added to later.
Part of https://github.com/wellcomecollection/platform/issues/5057
Depends:
- https://github.com/wellcomecollection/platform-infrastructure/pull/145
**Note:** this is applied.
> Manage DServe DNS

- accounts/workflow/iam_workflow_support.tf
- assets/iam_users.tf
- assets/s3_workingstorage.tf
For https://github.com/wellcomecollection/platform/issues/4885
These images have been copied to the storage service, and people should be downloading them from there instead – we sent out instructions several weeks ago, and warned people we'd be turning off access this week.
This change is applied, but I haven't deleted any objects yet.
> Remove access to the Miro images in workingstorage

- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.test.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.ts
- cloudfront/wellcomelibrary.org/terraform/locals.tf
This change will pass through requests to the old wellcome library site where there is no valid redirect, this is to help the Library API transition.
> Pass through if no valid redirect for Wellcome Library APIs

- accounts/platform/rolesets.tf
As Harrison is working more on catalogue stuff, we need to extend his permissions.
```diff
resource "aws_iam_role_policy" "role_assumer" {
id     = "data-dev:terraform-20190729114137699600000001"
name   = "terraform-20190729114137699600000001"
~ {
~ {
~ Resource = [
"arn:aws:iam::964279923020:role/data-developer",
+ "arn:aws:iam::964279923020:role/data-ci",
"arn:aws:iam::964279923020:role/data-admin",
"arn:aws:iam::760097843905:role/platform-developer",
+ "arn:aws:iam::756629837203:role/catalogue-read_only",
+ "arn:aws:iam::756629837203:role/catalogue-developer",
+ "arn:aws:iam::756629837203:role/catalogue-ci",
"arn:aws:iam::269807742353:role/reporting-read_only",
"arn:aws:iam::269807742353:role/reporting-developer",
+ …
```
> extend data dev to access catalogue account

- accounts/platform/.terraform.lock.hcl
- accounts/platform/rolesets.tf
Adding platform CI role to the data dev as they / Harrison needs it to run catalogue stuff locally. We need platform CI as the catalogue repo is still coupled to the platform account.
```diff
resource "aws_iam_role_policy" "role_assumer" {
id     = "data-dev:terraform-20190729114137699600000001"
name   = "terraform-20190729114137699600000001"
~ {
~ {
~ Resource = [
"arn:aws:iam::760097843905:role/platform-developer",
+ "arn:aws:iam::760097843905:role/platform-ci",
"arn:aws:iam::756629837203:role/catalogue-read_only",
]
},
]
}
)
}
```
> add platform CI role to data_dev

- accounts/identity/iam_identity_ci.tf
This allows the identity-ci role to assume itself – see comment for why this is useful.
In the immediate term, this is about fixing the tests on https://github.com/wellcomecollection/identity/pull/111
This change is already applied.
```
~ resource "aws_iam_role_policy" "identity_ci" {
id     = "identity-ci:terraform-20201119102354636800000001"
name   = "terraform-20201119102354636800000001"
~ {
{
Action   = "iam:PassRole"
Effect   = "Allow"
Resource = [
"arn:aws:iam::770700576653:role/identity-ecs-task-role-stage",
"arn:aws:iam::770700576653:role/identity-ecs-execution-role-stage",
]
Sid      = ""
},
+ {
+ Action   = "sts:AssumeRole"
+ Effect   = "Allow"
+ Resource = …
```
> Allow identity-ci to assume itself

- cloudfront/wellcomelibrary.org/edge-lambda/testRedirects.ts
- cloudfront/wellcomelibrary.org/terraform/cf_behaviours.tf
Item page redirections are being made available in the production environment as aprt of deceommisioning the wellcomelibrary.org site.
```
}
- ordered_cache_behavior {
- allowed_methods        = [
- "DELETE",
- "GET",
- "HEAD",
- "OPTIONS",
- "PATCH",
- "POST",
- "PUT",
] -> null
- cached_methods         = [
- "GET",
- "HEAD",
- "OPTIONS",
] -> null
- compress               = false -> null
- default_ttl            = 0 -> null
- max_ttl                = 0 -> null
- min_ttl                = 0 -> null
- path_pattern           = "item/*" -> null
- smooth_streaming       = false -> null
- target_origin_id       = "origin" -> null
- …
```
> Enable Item page redirects & tests

- assets/s3_workingstorage.tf
We have ~8TB of unhandled Miro images in `wellcomecollection-assets-workingstorage`.
* We can’t delete them indiscriminately – we'd be deleting the only copy of some images
* We can't compare them to the backups in `wellcomecollection-editorial-photography` – all those backups are lifecycled to Glacier, plus we'd need to spend way more time on this problem
See my comment on https://github.com/wellcomecollection/platform/issues/4885#issuecomment-816703253 for more explanation.
So for now, we'll push all these images off into Glacier Deep Archive – and restore them when we come back to put Editorial Photography images in the storage service. (Which is on the roadmap, but not the immediate one.)
The storage cost of Deep Archive is ~$100/year rather than $1250/year for Standard-IA. Retrieving …
> Move the unhandled Miro images to Glacier Deep Archive

- cloudfront/wellcomelibrary.org/edge-lambda/itemRedirects.csv
- cloudfront/wellcomelibrary.org/edge-lambda/src/bnumberToWork.test.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/bnumberToWork.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/catalogueApi.test.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/catalogueApi.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/catalogueApiFixtures.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/paths.test.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/paths.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/safeGet.test.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.test.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/wlorgpLookup.test.ts
- cloudfront/wellcomelibrary.org/terraform/cf_behaviours.tf
- cloudfront/wellcomelibrary.org/terraform/locals.tf
This redirects `/player` paths from the wellcomelibrary.org site, as these links (in addition to /item) are also displayed by encore (and "in the wild").
TBD
> /player redirects

- cloudfront/account.wellcomecollection.org/terraform/main.tf
This PR removes the `NS` record for `account.wellcomecollection.org` from the `wellcomecollection.org` root zone. The delegation of this hostname is being removed and records relating to `account.wellcomecollection.org` will instead be created directly against the root `wellcomecollection.org` zone.
This is work around an issue with Auth0 preventing us from creating the required `CNAME` record at the apex of the `account.wellcomecollection.org` zone.
```
- resource "aws_route53_record" "account-ns" {
- fqdn    = "account.wellcomecollection.org" -> null
- id      = "Z0902614YH73JBCZG1MA_account.wellcomecollection.org_NS" -> null
- name    = "account.wellcomecollection.org" -> null
- records = [
- "ns-1100.awsdns-09.org",
- "ns-1657.awsdns-15.co.uk",
- "ns-34.awsdns-04.com",
- …
```
> Removed the 'account.wellcomecollection.org' DNS delegation

- LICENSE.md
I got an email from somebody who wanted to use our script for mirroring images to ECR: https://github.com/wellcomecollection/platform-infrastructure/blob/master/images/publish_mirrored_images.py
They pointed out that there's no license in this repo – this PR adds that, same as our other repos.
> Add a LICENSE file

- accounts/identity/iam_identity_ci.tf
In order to publish SwaggerUI, the `identity-ci` IAM role needs permission to write to the newly created `identity-public-swagger-ui-v1-prod` bucket.
This PR also removes some redundant ECS permissions from the same IAM role.
```
~ resource "aws_iam_role_policy" "identity_ci" {
id     = "identity-ci:terraform-20201119102354636800000001"
name   = "terraform-20201119102354636800000001"
~ {
{
Action   = [
"s3:List*",
"s3:Get*",
]
Effect   = "Allow"
Resource = [
"arn:aws:s3:::identity-static-remote-state/*",
"arn:aws:s3:::identity-static-remote-state",
"arn:aws:s3:::identity-remote-state/*",
"arn:aws:s3:::identity-remote-state",
]
Sid      = ""
},
~ {
~ Resource = [ …
```
> Updated 'identity-ci' permissions following PROD deployment

- accounts/platform/rolesets.tf
@harrisonpim needs to be able to provision ecr image within the platform account.
I do wonder if maybe we have a less-than-admin account that allows for s3/ecr editing, but maybe that's too far. We should get on moving catalogue stuff across to the catalogue account. This is a bandaid to get the image inferrer work out.
```diff
~ resource "aws_iam_role_policy" "role_assumer" {
id     = "data-dev:terraform-20190729114137699600000001"
name   = "terraform-20190729114137699600000001"
~ {
~ {
~ Resource = [
"arn:aws:iam::760097843905:role/platform-ci",
+ "arn:aws:iam::760097843905:role/platform-admin",
"arn:aws:iam::756629837203:role/catalogue-read_only",
]
},
]
}
)
}
```
> add platform admin priveledges to data-dev

- accounts/digirati/outputs.tf
- accounts/digirati/vpcs.tf
Adding new VPC to Digirati AWS account to contain infra for [MoH](https://github.com/wellcomecollection/londons-pulse) migration work.
```hcl
+ resource "aws_vpc" "vpc" {
+ arn                              = (known after apply)
+ assign_generated_ipv6_cidr_block = false
+ cidr_block                       = "172.57.0.0/16"
+ default_network_acl_id           = (known after apply)
+ default_route_table_id           = (known after apply)
+ default_security_group_id        = (known after apply)
+ dhcp_options_id                  = (known after apply)
+ enable_classiclink               = (known after apply)
+ enable_classiclink_dns_support   = (known after apply)
+ enable_dns_hostnames             = true
+ enable_dns_support               = true
+ id                               = (known after …
```
> Add VPC for MoH migration

- accounts/experience/iam_experience_ci.tf
Allows experience-ci to read the items-api api keys so it can run tests.
**Note:** This is applied.
> Allow experience-ci to read api keys for items api

- cloudfront/wellcomelibrary.org/terraform/cf_behaviours.tf
- cloudfront/wellcomelibrary.org/terraform/cf_origins.tf
Makes changes to the MoH on prod.
We couldn't find any meaningful tests, as these aren't redirects, but rather pushing through to another service, that serves up almost identical content.
```
}
+ ordered_cache_behavior {
+ allowed_methods        = [
+ "DELETE",
+ "GET",
+ "HEAD",
+ "OPTIONS",
+ "PATCH",
+ "POST",
+ "PUT",
]
+ cached_methods         = [
+ "GET",
+ "HEAD",
+ "OPTIONS",
]
+ compress               = false
+ min_ttl                = 0
+ path_pattern           = "moh/*"
+ target_origin_id       = "moh_origin"
+ viewer_protocol_policy = "allow-all"
+ forwarded_values {
+ headers                 = [
+ …
```
> prodify the MOH

- critical/run_terraform.sh
This change makes it easier to use `run_terraform.sh` in the `critical` stack. 
Previously the terraform runner depended on a developer having a profile of a particular name, associated with the correct role. This change auto-creates a profile already associated with the correct role and uses that to get the secrets required to run `terraform`.
No changes.
> Auto-create profile in terraform runner

- accounts/identity/iam_identity_ci.tf
- accounts/identity/locals.tf
CI needs to read some secrets in order that it can run smoke tests.
```
~ resource "aws_iam_role_policy" "identity_ci" {
id     = "identity-ci:terraform-20201119102354636800000001"
name   = "terraform-20201119102354636800000001"
~ {
{
Action   = "ecs:RegisterTaskDefinition"
Effect   = "Allow"
Resource = "*"
Sid      = ""
},
+ {
+ Action   = "secretsmanager:GetSecretValue"
+ Effect   = "Allow"
+ Resource = [
+ "arn:aws:secretsmanager:eu-west-1:770700576653:secret:identity/stage/smoke_test/credentials",
+ "arn:aws:secretsmanager:eu-west-1:770700576653:secret:identity/stage/account_management_system/api_key",
+ "arn:aws:secretsmanager:eu-west-1:770700576653:secret:identity/prod/smoke_test/credentials",
+ …
```
> Identity CI needs to read some secrets

- builds/terraform/.terraform.lock.hcl
- builds/terraform/buildkite.tf
This adds permissions to buildkite to publish lambdas.
This is already applied to get the main build of catalogue-pipeline to pass
> Allow lambda publishing from ci

- builds/buildkite_agent_hook.sh
- builds/terraform/buildkite.tf
This change is already applied.
Currently nothing is running in CI because the spot price of the r5.large instances we use has just passed $0.04:
> Launching a new EC2 instance. Status Reason: Your Spot request price of 0.04 is lower than the minimum required Spot request fulfillment price of 0.0411. Launching EC2 instance failed.
Since this is only a small part of our bill ($72/mo), we can safely increase the spot bid without breaking the bank.
We also spent $126 last month on gp2 EBS volumes, most of which will be our BuildKite runners. I'm reasonably confident that we don't actually need 250GB per instance, so I've reduced it and added a check that will help us spot if a job failed due to low disk space.
> Tweak our BuildKite setup

- cloudfront/wellcomelibrary.org/terraform/locals.tf
Added some static redirects - this deploys them
```
}
~ default_cache_behavior {
- lambda_function_association {
- event_type   = "origin-request" -> null
- include_body = false -> null
- lambda_arn   = "arn:aws:lambda:us-east-1:760097843905:function:cf_edge_wellcome_library_redirect:69" -> null
}
+ lambda_function_association {
+ event_type   = "origin-request"
+ include_body = false
+ lambda_arn   = "arn:aws:lambda:us-east-1:760097843905:function:cf_edge_wellcome_library_redirect:72"
}
}
}
```
> bump redirect arn

- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.test.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.ts
Adding redirectes from `wl.org/collections/browse/*` => `wc.org/collections`.
Examples were taken from analytics.
Coming soon once code is reviewed.
> add redirections for collections/browse

- cloudfront/wellcomelibrary.org/edge-lambda/collectionsBrowse.csv
- cloudfront/wellcomelibrary.org/edge-lambda/testRedirects.ts
- cloudfront/wellcomelibrary.org/terraform/locals.tf
Making things proddy.
Test: https://stage.wellcomelibrary.org/collections/browse/wowzer
```
}
~ default_cache_behavior {
- lambda_function_association {
- event_type   = "origin-request" -> null
- include_body = false -> null
- lambda_arn   = "arn:aws:lambda:us-east-1:760097843905:function:cf_edge_wellcome_library_redirect:72" -> null
}
+ lambda_function_association {
+ event_type   = "origin-request"
+ include_body = false
+ lambda_arn   = "arn:aws:lambda:us-east-1:760097843905:function:cf_edge_wellcome_library_redirect:73"
}
}
}
```
> bump wl redirect lambda

- cloudfront/wellcomecollection.org/terraform/locals.tf
- cloudfront/wellcomecollection.org/terraform/main.tf
This change adds a CNAME record to have a custom domain for Statuspage (API & site status reporting tool) in order that we have a pleasant URL for our status page.
```
+ resource "aws_route53_record" "status" {
+ allow_overwrite = (known after apply)                                                                                                                       + fqdn            = (known after apply)
+ id              = (known after apply)
+ name            = "status.wellcomecollection.org"
+ records         = [
+ "qyhn8w55666p.stspg-customer.com",
]
+ ttl             = 300
+ type            = "CNAME"
+ zone_id         = "Z0902614YH73JBCZG1MA"
}
Plan: 1 to add, 0 to change, 0 to destroy.
```
> Add CNAME record for status.wellcomecollection.org

- cloudfront/wellcomelibrary.org/edge-lambda/archiveRedirects.csv
- cloudfront/wellcomelibrary.org/edge-lambda/src/bnumberToWork.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/catalogueApi.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/catalogueApiFixtures.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryArchiveRedirect.test.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryArchiveRedirect.ts
- cloudfront/wellcomelibrary.org/edge-lambda/testRedirects.ts
Ref: https://github.com/wellcomecollection/platform/issues/5058
Adds the redirects for `archives.wellcomecollection.org`.
The DServe application is a little fiddly, but there is some decernable information we can get from the QS.
In short
* `dsqItem` - which has a RefNo in it
* `dsqSearch`- can hold multiple types of search DSL. All search terms that are searched for are wrapped in `'`. We don't bother checking the field etc, we just take all the terms in `'`, join them on ` `, and search for it. If we find a matching ID in a work, we redirect to that work. If we don't, we search for the new search terms.
This should catch most URLs out there. The examples are taken from GA and Google searches, so real things that are happening.
No-op.
> Archive redirects

- cloudfront/wellcomelibrary.org/README.md
- cloudfront/wellcomelibrary.org/deploy
- cloudfront/wellcomelibrary.org/terraform/dserve.tf
- cloudfront/wellcomelibrary.org/terraform/locals.tf
Redirects archive.wellcomelibrary.org URLs because they are not wellcomecollection.org URLs.
Closes https://github.com/wellcomecollection/platform/issues/5058
```
+ resource "aws_cloudfront_distribution" "distro" {
+ aliases                        = [
+ "archives.wellcomelibrary.org",
]
+ arn                            = (known after apply)
+ caller_reference               = (known after apply)
+ comment                        = "Wellcome Library (archives.wellcomelibrary.org)"
+ domain_name                    = (known after apply)
+ enabled                        = true
+ etag                           = (known after apply)
+ hosted_zone_id                 = (known after apply)
+ http_version                   = "http2"
+ id                             = (known after apply)
+ …
```
> Redirect Dserve URLs 

- cloudfront/api.wellcomecollection.org/tests/Dockerfile
- cloudfront/iiif.wellcomecollection.org/tests/Dockerfile
Docker hub has unfortunate rate limits, ECR public may alleviate that issue while still not requiring authentication.
See https://docs.aws.amazon.com/AmazonECR/latest/public/public-service-quotas.html for quotas. These requests will primarily run from within AWS EC2:
```
10 (images pulls per second) for authenticated pulls or pulls to resources running on Amazon ECS, Fargate, or Amazon EC2
```
> Use ECR public repo for python

- accounts/README.md
- accounts/dam_prototype/account.tf
- accounts/dam_prototype/cloudhealth.tf
- accounts/dam_prototype/locals.tf
- accounts/dam_prototype/outputs.tf
- accounts/dam_prototype/provider.tf
- accounts/dam_prototype/terraform.tf
- accounts/dam_prototype/vpcs.tf
- accounts/identity/account.tf
- accounts/platform/locals.tf
- accounts/platform/rolesets.tf
- accounts/platform/terraform.tf
In order to support the DAM prototyping work (getting the storage service set up from scratch) this change adds a new AWS account to ringfence those resources.
> Add new AWS account for DAM Prototype

- cloudfront/wellcomelibrary.org/edge-lambda/passthruRedirects.csv
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryPassthru.test.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryPassthru.ts
- cloudfront/wellcomelibrary.org/edge-lambda/testRedirects.ts
Anything that passes though from wl.org will be redirected to wc.org. This will allow us to decommission the esrvers serving the apex domain.
This was the least amount of change to get what we want. There will be further tidy up PRs as with any far reaching redirect.
no-op until lambdas are buildt
> redirect passthru redirects to wellcomecollection.org

- cloudfront/wellcomelibrary.org/edge-lambda/passthruRedirects.csv
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryPassthru.test.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryPassthru.ts
- cloudfront/wellcomelibrary.org/edge-lambda/testRedirects.ts
I've misunderstood what goes where. 
The passthru was used by [behaviours](https://github.com/wellcomecollection/platform-infrastructure/blob/main/cloudfront/wellcomelibrary.org/terraform/cf_behaviours.tf#L2) that we wanted to passthru to wl.org. We no longer use them and should remove them.
This just get's us back into a state that we were previously, as this code should passthru to wl.org.
> Revert "redirect passthru redirects to wellcomecollection.org"

- cloudfront/wellcomelibrary.org/edge-lambda/testRedirects.ts
- cloudfront/wellcomelibrary.org/terraform/locals.tf
Bumps the redirect lambda
YOu can see a change here: stage.wellcomelibrary.org/things/not-here
```
}
~ default_cache_behavior {
- lambda_function_association {
- event_type   = "origin-request" -> null
- include_body = false -> null
- lambda_arn   = "arn:aws:lambda:us-east-1:760097843905:function:cf_edge_wellcome_library_redirect:73" -> null
}
+ lambda_function_association {
+ event_type   = "origin-request"
+ include_body = false
+ lambda_arn   = "arn:aws:lambda:us-east-1:760097843905:function:cf_edge_wellcome_library_redirect:76"
}
}
}
```
> bump tf redirect lambda

- accounts/platform/iam_platform_ci.tf
- builds/terraform/buildkite.tf
Allowing BuildKite to publish to `weco` instead of `uk/ac/wellcome`. For wellcomecollection/platform#4690
> Allow CI to publish Scala libraries to the weco namesapce

- images/publish_mirrored_images.py
- images/terraform/ecr.tf
- images/terraform/repo_pair/main.tf
This is part of some work to expunge the typesafe_config_base container: https://github.com/wellcomecollection/platform/issues/4619
> Mirror the java11 Docker image into our ECR repositories

- cloudfront/wellcomelibrary.org/edge-lambda/src/catalogueApi.ts
We are currently seeing lambdas@edge running for more than 3 seconds, thus 503ing to users.
The place where most the time is spent in the lamda is queries with loads of results that [we paginate through all the results](https://github.com/wellcomecollection/platform-infrastructure/blob/main/cloudfront/wellcomelibrary.org/edge-lambda/src/catalogueApi.ts#L66) searching for an ID.
This PR minimises the amount of time spent in a lambda by
* Only search the identifiers field, so queries like `MS 542` [return 0 results](https://api.wellcomecollection.org/catalogue/v2/works?include=identifiers&pageSize=100&identifiers=MS%20542) rather [than hundreds](https://api.wellcomecollection.org/catalogue/v2/works?include=identifiers&pageSize=100&query=MS%20542), and we still have the [ID search …
> use identifier search over free text search

- cloudfront/wellcomelibrary.org/terraform/locals.tf
[This is working](https://archives.stage.wellcomelibrary.org/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqCmd=Show.tcl&dsqDb=Catalog&dsqPos=0&dsqSearch=((AltRefNo=%27MS%27)AND(AltRefNo=%27542%27))), so we're deploying it.
```
id                             = "E2ECIIHB6JOYND"
}
~ default_cache_behavior {
- lambda_function_association {
- event_type   = "origin-request" -> null
- include_body = false -> null
- lambda_arn   = "arn:aws:lambda:us-east-1:760097843905:function:cf_edge_wellcome_library_archive_redirect:22" -> null
}
+ lambda_function_association {
+ event_type   = "origin-request"
+ include_body = false
+ lambda_arn   = …
```
> bump prod archive lambda

- critical/elastic_logging_cluster.tf
- critical/terraform.tf
Updates the logging clusters terraform provisioner, and elastic version.
The interface is nicer for kibana and a few changes have been made to kibana alerting, and I'd rather be working to the latest than having to update later.
```
~ resource "ec_deployment" "logging" {
id                     = "f4c9aca09347dad4c05f35cfbec04cdb"
name                   = "logging"
~ version                = "7.11.2" -> "7.13.3"
}
```
> bump ec provisioner and es version on logging cluster

- images/publish_mirrored_images.py
- images/terraform/ecr.tf
- images/terraform/repo_pair/main.tf
I'm binning the mirrored ECR Wiremock repository to closed https://github.com/wellcomecollection/platform/issues/5192, because we no longer use Wiremock in our tests.
```
- resource "aws_ecr_repository" "mirrored_images" {
- arn                  = "arn:aws:ecr:eu-west-1:760097843905:repository/rodolpheche/wiremock" -> null
- id                   = "rodolpheche/wiremock" -> null
- image_tag_mutability = "MUTABLE" -> null
- name                 = "rodolpheche/wiremock" -> null
- registry_id          = "760097843905" -> null
- repository_url       = "760097843905.dkr.ecr.eu-west-1.amazonaws.com/rodolpheche/wiremock" -> null
- tags                 = {} -> null
- tags_all             = {} -> null
- encryption_configuration {
- encryption_type = …
```
> Remove the mirrored Wiremock ECR repository

- critical/.terraform.lock.hcl
- critical/elastic_logging_cluster.tf
Real User Monitoring support is not enabled by default in APM - this flicks the switch.
```
~ resource "ec_deployment" "logging" {
id                     = "f4c9aca09347dad4c05f35cfbec04cdb"
name                   = "logging"
~ apm {
+ config {
+ debug_enabled      = false
+ user_settings_yaml = <<-EOT
"apm-server":
"rum":
"enabled": true
EOT
}
}
}
```
> Enable Elastic APM RUM

- images/nginx/experience.nginx.conf
This is necessary for the Lighthouse server, which sometimes receives requests that are slightly larger than 1m (the default)
> Increase client_max_body_size for experience nginx

- accounts/identity/iam_identity_ci.tf
- accounts/identity/locals.tf
In order to easily deploy changes the Auth0 universal-login interface, this change adds permissions for identity-ci to deploy universal-login.
**Note:** this is applied
> Update identity-ci permissions to deploy universal-login

- critical/elastic_logging_cluster.tf
- critical/outputs.tf
- critical/secrets.tf
This exposes the APM server URL and secret token using the existing mechanisms for shared secrets
Note: this plan does not include the shared secrets (ie using `modules/secrets/distributed`) because they are dependent on the initial secrets.
```
+ resource "aws_secretsmanager_secret" "secret" {
+ arn                     = (known after apply)
+ id                      = (known after apply)
+ name                    = "elasticsearch/logging/apm_secret"
+ name_prefix             = (known after apply)
+ policy                  = (known after apply)
+ recovery_window_in_days = 30
+ rotation_enabled        = (known after apply)
+ rotation_lambda_arn     = (known after apply)
+ tags_all                = {
+ "TerraformConfigurationURL" = …
```
> Shared secrets for APM params

- accounts/platform/rolesets.tf
This change removes access to the Identity AWS account for "dev" roleset, and from Digirati developers.
```
~ resource "aws_iam_role_policy" "role_assumer" {
id     = "platform-dev:terraform-20190701095808272400000001"
name   = "terraform-20190701095808272400000001"
~ {
~ {
~ Resource = [
"arn:aws:iam::964279923020:role/data-ci",
- "arn:aws:iam::770700576653:role/identity-read_only",
- "arn:aws:iam::770700576653:role/identity-developer",
"arn:aws:iam::760097843905:role/terraform-20210811133135108800000001",
"arn:aws:iam::760097843905:role/platform-ci",
- "arn:aws:iam::760097843905:role/ci-agent",
"arn:aws:iam::756629837203:role/catalogue-read_only",
]
},
]
}
)
}
~ resource "aws_iam_role_policy" …
```
> Restrict identity access to platform-superdev

- builds/terraform/buildkite.tf
For https://github.com/wellcomecollection/platform/issues/5288. There's an accompanying storage service PR to come.
> Allow BuildKite to get storage-service credentials

- builds/terraform/buildkite.tf
- builds/terraform/locals.tf
We get a second pool of Buildkite runners which are t3.nano instances instead of r5.large. For long-running or small tasks that don't need a lot of CPU power, we can pick these runners instead, which should make CI quite a bit less spendy.
For https://github.com/wellcomecollection/platform/issues/5289
> Create a Buildkite stack for "nano" jobs

- .buildkite/pipeline.yml
This is what we do in all our other repos – it means that if autoformat pushes a commit, we're not wasting build time on tests with unformatted code.
> Wait until autoformat is done before running tests

- monitoring/terraform/modules/slack_alert_on_cloudfront_errors/main.tf
- monitoring/terraform/slack_alert_on_cloudfront.tf
Make these alarms stop spamming our Slack channel and hiding real errors.
> Disable the experience CloudFront alarms

- builds/terraform/buildkite.tf
So we don't get held up waiting for nano instances while trying to deploy from the pipeline repo.
This is something I spotted while working on https://github.com/wellcomecollection/platform/issues/5315.
> Double the max number of Buildkite nano instances to 10

- builds/terraform/buildkite.tf
Last month we spent ~$75 on r5.large instances and ~$100 on gp2 volumes. Our BuildKite setup is also imbalanced:
* It's possible to max out our 30 workers. At peak build times, you can be waiting 20m+ for your build to start. Slow!
* 150GB is massive, a quick spin through our current worker pool suggests they have ~144GB or so free with a warm cache (this is logged as part of our pre-job hook). Wasteful!
This change tries to rebalance that spending: take some of the money we're spending on gp2 volumes, and spend it on running more workers instead. I don't expect it to impact the bill much, but it should avoid our builds getting throttled because too many people are building at once.
> Double the number of Buildkite instances at peak; reduce disk usage

- builds/terraform/buildkite.tf
> give buildkite agents access to rank credential secrets

- builds/terraform/buildkite.tf
Adds access to the prismic-model Prismic API keys for [this](https://github.com/wellcomecollection/wellcomecollection.org/pull/7282)
> Allow CI access to prismic API keys

- cloudfront/api.wellcomecollection.org/cloudfront_distro/main.tf
This should mitigate the impact of somebody inadvertently hammering the /works API, with minimal impact on result freshness.
(This is deployed.)
> Cache results from api.wc.org for 10 seconds at a time

- images/nginx/README.md
- images/nginx/apigw.Dockerfile
- images/nginx/experience.Dockerfile
- images/nginx/frontend.nginx.conf
- images/nginx/grafana.Dockerfile
- images/nginx/template.Dockerfile
- images/publish_nginx_images.sh
What this does:
- Builds all the Nginx images with the same base Dockerfile
- Renames `experience` to `frontend` to make intentions clearer
- Pushes all images to ECR Public (@alexwlchan is there a reason we were only doing it for apigw?)
> Standardise nginx images

- cloudfront/wellcomelibrary.org/edge-lambda/src/csvFixtures/encoreRedirects.csv
- cloudfront/wellcomelibrary.org/edge-lambda/testRedirects.ts
- cloudfront/wellcomelibrary.org/terraform/lambdas.tf
The name of the entrypoint in the Lambda function was wrong, so the Lambda function wasn't running.  I've also added the first bit of a test harness for testing Encore redirects.
For https://github.com/wellcomecollection/platform/issues/4977
> Fix the redirects on search.stage.wl.org

- cloudfront/wellcomelibrary.org/edge-lambda/src/csvFixtures/encoreRedirects.csv
- cloudfront/wellcomelibrary.org/edge-lambda/src/paths.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/redirectHelpers.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/tests/wellcomeLibraryEncoreRedirect.test.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryEncoreRedirect.ts
- cloudfront/wellcomelibrary.org/edge-lambda/src/wellcomeLibraryRedirect.ts
This adds the redirects described in wellcomecollection/platform#5056; follows #276
It's not deployed anywhere yet (either stage or prod), but the business logic is there. We'll also get logs about any paths we aren't redirecting successfully, so we can add more later if necessary.
> Create redirections for the known Encore URL patterns

- images/dockerfiles/sbt_wrapper/Dockerfile
- images/dockerfiles/sbt_wrapper/README.md
- images/dockerfiles/sbt_wrapper/install_docker_compose.sh
- images/dockerfiles/sbt_wrapper/install_sbt.sh
- images/dockerfiles/sbt_wrapper/populate_sbt_cache.py
- images/dockerfiles/sbt_wrapper/run_sbt.sh
Working with Paul this week, I've been acutely aware of how slow our Scala builds still are. I remember the bad old days of multi-hour builds, and while our current ~15m build times are fast*er*, they're still not *fast*.
All of our Scala builds invoke sbt through an `sbt_wrapper` image (previously defined in [our dockerfiles repo](https://github.com/wellcomecollection/dockerfiles/blob/main/sbt_wrapper/Dockerfile), which has become very stale). Since it's on the hot path, I decided to see if I could make it faster.
I've done this in two ways:
1.  The final image is smaller: <s>~1.15GB</s> ~770MB compared to ~2GB.
Still not small, but smaller.  This is achieved by starting from a smaller base image and removing dependencies that are only used for building the image, not running it. …
> Replace our sbt_wrapper Docker image with a smaller, faster one

- monitoring/README.md
Since Jamie was asking how our Lambda error alerting works, I scribbled a few words here.
There are also notes in the `slack_alerts` folder, but they're a bit more "how to deploy these".
> Add a bit of explanation of how our monitoring Lambdas work

- monitoring/slack_alerts/metric_to_slack_alert/src/metric_to_slack_alert.py
- monitoring/terraform/modules/slack_alert_on_cloudfront_errors/main.tf
- monitoring/terraform/modules/slack_alert_on_cloudfront_errors/variables.tf
- monitoring/terraform/s3.tf
- monitoring/terraform/slack_alert_on_cloudfront.tf
This is an optional field that lets us point to URLs that might give
more context for an error, e.g. Kibana logs for a failing app.  This link
will appear in Slack, to make it easier for devs to debug issues.
> Allow setting a context URL in our metric Lambda

- monitoring/slack_alerts/metric_to_slack_alert/src/metric_to_slack_alert.py
The links to Kibana in Slack often don't include the relevant logs - this should fix that
> Expand logs window that is linked to in Slack alerts

- monitoring/slack_alerts/lambda_errors_to_slack_alerts/src/lambda_errors_to_slack_alerts.py
So that cases like https://github.com/wellcomecollection/identity/pull/269 throw informative error messages
> Enforce the Lambda alarm naming convention

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
This also adds some (defensive) redaction for logging, in case any PII makes it to the reporting Lambda via the descriptions. I haven't seen any evidence of this happening or really being possible, but it pays to be careful!
> Filter out "You may have pressed the back button" errors

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
These are now covered by our error messaging
> Exclude PIN-triviality errors

- accounts/platform/iam_platform_ci.tf
- monitoring/slack_alerts/metric_to_slack_alert/src/metric_to_slack_alert.py
For https://github.com/wellcomecollection/platform/issues/5481
This allows the catalogue API diff tool to query the per-pipeline clusters, rather than going to the API cluster.
> Allow the platform-ci role to get pipeline-storage secrets

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
These errors are noisy and are expected behaviour
> Don't alert on invalid refresh token errors

- cloudfront/invalidation/lambda/Dockerfile
For wellcomecollection/platform#5545, which includes a discussion of the benefits.
> Use a Node image from ECR Public, not Docker Hub

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
If users try to sign up with a common password, we don't need to know about it in the alerts channel.
> Don't alert on failed signup if it's for a known reason

- cloudfront/api.wellcomecollection.org/tests/Dockerfile
- cloudfront/iiif.wellcomecollection.org/edge-lambda/Dockerfile
- cloudfront/iiif.wellcomecollection.org/edge-lambda/package.json
- cloudfront/iiif.wellcomecollection.org/tests/Dockerfile
This fixes the failing tests on #305.
> Remove a use of a Node image from our private ECR repos

- accounts/modules/account/federated/outputs.tf
- accounts/modules/account/federated/variables.tf
- accounts/modules/cloudhealth/cloudhealth-role.tf
- accounts/platform/.terraform.lock.hcl
- accounts/platform/account.tf
- accounts/platform/provider.tf
- accounts/platform/s3_editorial_photography.tf
- accounts/platform/terraform.tf
For https://github.com/wellcomecollection/platform/issues/5557
I had to change the SAML file yesterday so it's fresh in my mind; I didn't realise it was configured in Terraform or I'd have handled it there.
It took a bit of finagling to let Terraform remove it – I tried removing the resources and running `terraform init`, but it wouldn't budge. Then I used `terraform providers` to see it was being pulled in through the state but not any resources; I ran `terraform apply -refresh-only` and then `terraform init`, and that removed it.
> Remove the deprecated template provider from the platform accounts

- monitoring/terraform/.terraform.lock.hcl
- monitoring/terraform/modules/efs_host/main.tf
- monitoring/terraform/modules/ondemand/asg.tf
- monitoring/terraform/stack/grafana/main.tf
- monitoring/terraform/stack/grafana/task_definition/container_definition.tf
- monitoring/terraform/stack/grafana/task_definition/outputs.tf
- monitoring/terraform/stack/grafana/task_definition/secrets/iam.tf
- monitoring/terraform/stack/grafana/task_definition/secrets/main.tf
- monitoring/terraform/stack/grafana/task_definition/secrets/outputs.tf
- monitoring/terraform/stack/grafana/task_definition/secrets/variables.tf
- monitoring/terraform/stack/grafana/task_definition/task_definition.json.tpl
- monitoring/terraform/stack/grafana/task_definition/task_definition.tf
- monitoring/terraform/stack/grafana/task_definition/variables.tf
For https://github.com/wellcomecollection/platform/issues/5557
I think this should allow @melanierogan to use Terraform on her M1 MacBook without getting warnings about an unavailable provider. 🤞 I've had to inline the module which defines our Grafana instance, which is v old – tbh we should probably move this to managed Grafana or similar, but it's never been high enough priority.
> Remove the template provider from the monitoring stack

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
As we are happy this kind of alert is handled in the frontend i.e. the user who is changing their password will know what to do based on ui messaging on not using repeated characters, we don't need to have the alert on when this happens coming to slack.
The last two of these changes don't look familiar to me and I wonder if they're related to the change I made to `auth0_log_stream_alerts`.
```Terraform will perform the following actions:
id                             = "identity_auth0_log_stream_alerts"
~ last_modified                  = "2022-06-09T10:46:48.000+0000" -> (known after apply)
~ source_code_hash               = REDACTED
}
~ resource "aws_iam_role_policy" "cloudwatch_logs" {
id     = …
```
> Updating auth0 slack alerts to omit 'PIN is trivial' alert

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
We've discussed changing this before, let's actually do it.
> Don't warn on API rate limiting in staging

- images/dockerfiles/nginx/frontend.nginx.conf
- images/dockerfiles/nginx/frontend_identity.nginx.conf
- images/dockerfiles/publish_nginx_images.sh
- images/terraform/ecr.tf
For https://github.com/wellcomecollection/wellcomecollection.org/issues/8121
This creates a new nginx image solely for use by the identity web app, which redacts certain query parameters which we know will contain PII.
Before:
> 172.19.82.22 - - [04/Jul/2022:12:55:50 +0000] "GET /account/success?email=**alex@alexwlchan.net** HTTP/1.1" 200 47350 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15"
After:
> 172.19.12.51 - - [04/Jul/2022:13:17:16 +0000] www-stage.wellcomecollection.org "GET /account/success?email=**[redacted]**" 200 47351 0.535 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15" "79.68.63.8, 64.252.152.81"
> Create an nginx Docker image that redacts PII in query parameters

- images/dockerfiles/sbt_wrapper/run_sbt.sh
This verbosity is a pain when you want piped command output, and doesn't add much value
> SBT wrapper should not be verbose

- accounts/identity/iam_identity_ci.tf
They're defined in the identity repo now. Part of https://github.com/wellcomecollection/identity/issues/372
> Remove the smoke test permissions for the identity CI

- cloudfront/wellcomecollection.org/terraform/main.tf
Adding a CNAME record pointing at `domains.chromatic.com` so that whatever version of  Chromatic Storybook is currently in the main branch of `wellcomecollection.org` will available at `cardigan.wellcomecollection.org`.
```
+ resource "aws_route53_record" "cardigan" {
+ allow_overwrite = (known after apply)
+ fqdn            = (known after apply)
+ id              = (known after apply)
+ name            = "cardigan.wellcomecollection.org"
+ records         = [
+ "domains.chromatic.com",
]
+ ttl             = 300
+ type            = "CNAME"
+ zone_id         = "Z0902614YH73JBCZG1MA"
}
Plan: 1 to add, 0 to change, 0 to destroy.
```
> Add CNAME record for cardigan chromatic

- cloudfront/wellcomecollection.org/terraform/main.tf
Adding redirects for alpha.wc.org and blog.wc.org, which are both defunct subdomains we want to be redirecting to the new site.
For https://github.com/wellcomecollection/wellcomecollection.org/issues/8273; for https://github.com/wellcomecollection/platform/issues/4462
Already applied.
> Add redirects for alpha.wc.org and blog.wc.org

- images/terraform/repo_policy/main.tf
This is needed for [the ](https://github.com/wellcomecollection/platform/issues/5597)
> Allow other accounts to use ecr:DescribeImages on shared images

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
This is what a log event with this error looks like:
{
"type": "fs",
"description": "Password is too common",
"details": {
"description": "Password is not allowed, it might be too common.",
…
},
…
}
The previous string was matching on `details.description`, but in fact this Lambda receives `description`, so that's what we should be checking.
See https://github.com/wellcomecollection/identity/blob/main/infra/scoped/auth0-logs.tf#L55
> Make sure we actually filter out 'password too common' errors

- monitoring/terraform/modules/slack_alert_on_cloudfront_errors/main.tf
The issue with Terraform wanting to update IAM permissions indicates a bug in the way we've set up these Lambdas; in particular:
*   We have a Lambda to catch Lambda errors in experience/eu-west-1
(which is where most of our Lambdas live)
*   We have a Lambda to catch Lambda errors in experience/us-east-1
(which is where our CloudFront Lambdas live)
This Lambda includes an IAM role which allows them to write to their own DLQ (so they can report on their own errors), and IAM roles are globally unique.  Before this patch, both Lambdas had roles with the same name, so they were fighting over whose queue they'd be allowed to write to.
This tweaks the names so the Lambda in us-east-1 has a different name, which means it has a different IAM role.  This means they're no longer blatting each …
> Separate the Lambda that alerts on us-east-1 Lambda errors

- monitoring/slack_alerts/metric_to_slack_alert/src/metric_to_slack_alert.py
- monitoring/terraform/modules/slack_alert_on_sqs_dlq/main.tf
Until now, DLQ alerts are triggered when there is something on the DLQ, whether this is 1 or 1 million.
Having a few missed records is not a significant problem and can be dealt with at leisure, so the alerts are just a warning.
However, when the number of messages on a DLQ gets really big, it can indicate that something is very wrong with the pipeline.
With this change, an alert that was just a warning before, becomes an error with a different message once the number of failed messages breaches a threshold (10,000)
```
~ resource "aws_security_group" "external_lb_security_group" {
id                     = "sg-0c372a2ddc3f9e09d"
~ ingress                = (sensitive)
name                   = …
```
> add superplural criteria to dlq alerts

- accounts/modules/role_policies/ci/policies.tf
Some services in the concepts pipeline will be running on Lambda (this approach might be extended elsewhere), so CI needs to be able to update the lambda code when it changes.
```
~ resource "aws_iam_role_policy" "ci_permissions" {
id     = "catalogue-ci:terraform-20200713113726102900000001"
name   = "terraform-20200713113726102900000001"
~ {
~ {
~ Action   = [
"sts:GetServiceBearerToken",
+ "lambda:UpdateFunctionCode",
+ "lambda:GetFunctionConfiguration",
"ecr:UploadLayerPart",
]
},
{
Action   = "s3:*"
Effect   = "Allow"
Resource = [
"arn:aws:s3:::wellcomecollection-catalogue-infra-delta/*",
"arn:aws:s3:::wellcomecollection-catalogue-infra-delta",
]
Sid      = ""
},
]
}
)
}
```
> allow ci to update lambdas

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
* Ignore errors about "too long password", which we can't fix
* Pass a couple of descriptions through to Slack so debugging can start without logging in to Auth0
> More improvements to the Auth0 alerts

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
When we created nicer user-facing errors for some common Auth0 problems (e.g. Sierra wants a more complex password), those errors started to slip through our alerting into Slack again.  This updates the alerting Lambda to filter out these alerts again, so we don't get warned about benign issues.
This is already applied.
> Filter out some of the benign Auth0 alerts

- accounts/modules/vpc/main.tf
- accounts/modules/vpc/nat/outputs.tf
- accounts/modules/vpc/public-private-igw/outputs.tf
- accounts/platform/outputs.tf
[Our CI instances are in private subnets within the CI VPC](https://github.com/wellcomecollection/buildkite-infrastructure/blob/main/terraform/buildkite.tf#L227-L229), which is owned by the platform account. This VPC has a (managed) NAT gateway on the route table, and as such all requests made by CI agents come from the NAT's (public) Elastic IP address.
If we want to identify requests made by these agents (for example, so our WAF rules don't block them), we need to know what that EIP is - this PR exposes it as an output which we will then be able to get from remote state.
As an aside, our CI agents do also have their own public IP addresses assigned - I think this is possible because, despite them being in private subnets, the VPC does contain public subnets. Because of the NAT gateway, …
> Expose the CI VPC NAT's EIP

- accounts/modules/role_policies/ci/policies.tf
These were used for managing deployments with weco-deploy, which we're not using any more, so these perms can be removed. Strictly speaking it does no harm to leave them there, but it's liable to cause confusion for anybody looking at this policy in future.
I haven't applied this yet.
For https://github.com/wellcomecollection/platform/issues/5631
Example from planning in the platform account, where it looks like maybe some Lambda permissions haven't been applied consistently yet:
```
~ resource "aws_iam_role_policy" "ci_permissions" {
id     = "platform-ci:terraform-20200713113726104100000001"
name   = "terraform-20200713113726104100000001"
~ {
~ {
~ Action   = [
"sts:GetServiceBearerToken",
+ "lambda:UpdateFunctionCode",
+ …
```
> Remove IAM permissions for the wellcome-releases-* tables

- images/terraform/ecr.tf
Removing an ECR repository for a tool we no longer use. For https://github.com/wellcomecollection/platform/issues/5631
```
- resource "aws_ecr_repository" "mirrored_images" {
- arn                  = "arn:aws:ecr:eu-west-1:760097843905:repository/wellcome/weco-deploy" -> null
- id                   = "wellcome/weco-deploy" -> null
- image_tag_mutability = "MUTABLE" -> null
- name                 = "wellcome/weco-deploy" -> null
- registry_id          = "760097843905" -> null
- repository_url       = "760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy" -> null
- tags                 = {} -> null
- tags_all             = {} -> null
- encryption_configuration {
- encryption_type = "AES256" -> null
}
- image_scanning_configuration { …
```
> We don't need to maintain an ECR repo for weco-deploy

- accounts/platform/rolesets.tf
```
~ resource "aws_iam_role_policy" "role_assumer" {
id     = "data-dev:terraform-20190729114137699600000001"
name   = "terraform-20190729114137699600000001"
~ {
~ {
~ Resource = [
"arn:aws:iam::269807742353:role/reporting-ci",
+ "arn:aws:iam::130871440101:role/experience-read_only",
+ "arn:aws:iam::130871440101:role/experience-developer",
]
},
]
}
)
}
```
> Allow data-dev access to experience account

- .buildkite/scripts/run_autoformat.sh
- accounts/modules/elastic_log_forwarder/config.yml.tftpl
- accounts/modules/elastic_log_forwarder/main.tf
- accounts/modules/elastic_log_forwarder/variables.tf
- accounts/platform/logging.tf
- accounts/platform/terraform.tf
- critical/elastic_logging_cluster.tf
- critical/modules/elasticsearch_data_stream/main.tf
- critical/modules/elasticsearch_data_stream/outputs.tf
- critical/modules/elasticsearch_data_stream/provider.tf
- critical/modules/elasticsearch_data_stream/variables.tf
- critical/outputs.tf
This provisions (a) an [Elastic serverless forwarder](https://github.com/elastic/elastic-serverless-forwarder), (b) a data stream in the logging cluster for it to put logs into, and (c) a Kinesis stream that it subscribes to.
It's kind of non-trivial to test this, as there is a bit of an IAM dance for sending logs from a Lambda to the Kinesis stream. I'll build a module to do this separately, and then probably need to come back here to tweak.
> Elastic serverless forwarder

- critical/elastic_logging_cluster.tf
- critical/lambda_logging.tf
- critical/locals.tf
- critical/modules/elastic_log_forwarder/config.yml.tftpl
- critical/modules/elastic_log_forwarder/main.tf
- critical/modules/kinesis_log_destination/README.md
- critical/modules/kinesis_log_destination/kinesis.tf
- critical/modules/kinesis_log_destination/log_destination.tf
- critical/modules/kinesis_log_destination/outputs.tf
- critical/modules/kinesis_log_destination/variables.tf
- critical/provider.tf
This makes it possible to send logs to Kinesis from any account, and also fixes the ESF configuration.
> Configure the Kinesis stream with a cross-account log destination

- images/publish_mirrored_images.py
- images/terraform/ecr.tf
For https://github.com/wellcomecollection/platform/issues/5370
We don't use this image anywhere any more, so we can get rid of it; see https://github.com/search?type=Code&q=org:wellcomecollection+build_test_python
> Remove references to the build_test_python image

- .buildkite/pipeline.redirectsTest.yml
- cloudfront/iiif.wellcomecollection.org/terraform/cert.tf
- cloudfront/iiif.wellcomecollection.org/terraform/cf_behaviours.tf
- cloudfront/iiif.wellcomecollection.org/terraform/cf_origins.tf
- cloudfront/iiif.wellcomecollection.org/terraform/main.tf
- cloudfront/iiif.wellcomecollection.org/terraform/origin_sets/origin_set.tf
- cloudfront/iiif.wellcomecollection.org/terraform/outputs.tf
- cloudfront/iiif.wellcomecollection.org/tests/rewrite_tests.py
- cloudfront/invalidation/terraform/iam.tf
- cloudfront/invalidation/terraform/locals.tf
- cloudfront/invalidation/terraform/main.tf
(WIP)
This adds Cloudfront configuration for routing to an additional complete DDS environment, `iiif-stage-new.wellcomecollection.org`, alongside `iiif`, `iiif-stage` and `iiif-test`, as well as routing asset (image service, AV, born digital) DLCS requests to `neworchestrator.dlcs.io` rather than `dlcs.io`.
TBC
Questions:
- Does the Edge Lambda need anything extra?
- What needs to go in [cf_behaviours.tf](https://github.com/wellcomecollection/platform-infrastructure/blob/main/cloudfront/iiif.wellcomecollection.org/terraform/cf_behaviours.tf) ? It currently has `prod` and `stage` configuration but NOT `test`.
- Similarly [locals.tf](https://github.com/wellcomecollection/platform-infrastructure/blob/main/cloudfront/iiif.wellcomecollection.org/terraform/locals.tf) doesn't have `test` but …
> Initial cloudfront config for iiif-stage-new

- .buildkite/pipeline.redirectsTest.yml
Remove `iiif-stage-new.wc.org` tests from buildkite config. Config added in #349 but for these tests to path a collection of known assets need to exist in the DLCS. This isn't the case for iiif-stage-new as it uses an empty DLCS instance, which is only being used for integration testing.
Tests can be reinstated at a later date when we have required assets ingested into the DLCS.
_No TF changed_
> Remove redirect tests for iiif-stage-new.wc.org

- images/publish_mirrored_images.py
- images/terraform/ecr.tf
I continue to aspire towards ditching all these mirrored images entirely; in the meantime these are two images we don't use any more, so we can delete their mirrored versions.
For https://github.com/wellcomecollection/platform/issues/5370/https://github.com/wellcomecollection/platform/issues/5545
> Remove a couple of mirrored images that we're no longer using

- accounts/platform/locals.tf
- accounts/platform/rolesets.tf
This adds the legacy 'microsite' account to our standard roleset, so any platform dev can log in and do maintenance as necessary. We don't do much in here, but I just had to add the CloudHealth role for D&T, and it was easier to make it like everything else than carve out a special exception.
> Add our standard role permissions to the microsites account

- cloudfront/invalidation/terraform/iam.tf
- cloudfront/invalidation/terraform/locals.tf
Currently the DDS WorkflowProcessor can publish to an SNS topic to trigger a CloudFront invalidation Lambda. This happens as a post-processing step after a work has been handled. 
We want to allow an invalidation to be triggered via the DDS Dashboard without needing to process the work first. This PR adds the dashboard task-role Id to the relevant `aws_sns_topic_policy` to enable this.
See ticket: https://github.com/wellcomecollection/platform/issues/5627
I wasn't expecting the `aws_lambda_function` changes to appear in the following change list but they are there when I run a plan on `main` without any changes.
<details>
<summary>output of <code>terraform plan -no-color</code></summary>
```hcl
~ resource "aws_sns_topic_policy" "api_prod" {
id …
```
> DDS dashboard task-role can publish to SNS invalidation topic

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
> Filter out more "change password" alerts when it's the user fault

- cloudfront/api.wellcomecollection.org/cloudfront_distro/main.tf
- cloudfront/api.wellcomecollection.org/cloudfront_distro/variables.tf
- cloudfront/api.wellcomecollection.org/main.tf
Part of https://github.com/wellcomecollection/content-api/issues/2
This is already applied for stage, and the config is pre-emptively there for prod. It's pretty much a copy/paste of the existing config that's there for the catalogue API.
> Add origin and behaviour for the Content API

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
> Ignore alerts about somebody having too common a password

- cloudfront/iiif.wellcomecollection.org/edge-lambda/Dockerfile
- cloudfront/iiif.wellcomecollection.org/edge-lambda/package.json
- cloudfront/invalidation/lambda/Dockerfile
- cloudfront/invalidation/lambda/package.json
The tests are failing and we're running old versions of Node, I suspect these are related facts.
> Bump the Node versions in the Lambdas to fix failing tests

- accounts/modules/account/aws/qualys.tf
- accounts/modules/qualys/main.tf
- accounts/modules/qualys/policies.tf
- accounts/platform/.terraform.lock.hcl
This is adding a standard IAM role to all our accounts, which allows the Qualys vulnerability scanning tool being used by the InfoSec team to scan EC2 instances in our accounts.
(I suspect they won't find much as we run very little vanilla EC2, but this role is pretty innocuous and it seems fine to me.)
> Add the Qualys EC2 scanning role for D&T

- cloudfront/iiif.wellcomecollection.org/terraform/cf_origins.tf
The DLCS origin for `iiif-test.weco.org` is using a backup of the production db so we want to use space 5 to mimic prod space.
These same origin were recently changed in #382 to test iiif-builder/dds
_Unable to plan due to permissions_
> Update space used by iiif-test

- cloudfront/iiif.wellcomecollection.org/terraform/cert.tf
- cloudfront/iiif.wellcomecollection.org/terraform/cf_origins.tf
- cloudfront/iiif.wellcomecollection.org/terraform/main.tf
- cloudfront/iiif.wellcomecollection.org/terraform/origin_sets/origin_set.tf
- cloudfront/iiif.wellcomecollection.org/terraform/outputs.tf
- cloudfront/iiif.wellcomecollection.org/tests/rewrite_tests.py
- cloudfront/invalidation/terraform/iam.tf
- cloudfront/invalidation/terraform/locals.tf
- cloudfront/invalidation/terraform/main.tf
We have now released new versions of iiif-builder/dds and DLCS. This change rollsback some temporary changes that were made to lower environments to facilitate testing. Changes:
* Remove iiif-stage-new.weco.org CF distro. This was a temporary environment that has been deleted.
* Remove resources related to invalidating above CF distro.
* Update iiif-test.weco.org origins:
* Use `dlcs.io` rather than `neworchestrator.dlcs.io`. Latter was an alias for Protagonist before it was deployed to production.
* Use space 9, rather than 5. Space 5 is "production", space 9 is "test"
Unable to plan changes to CF distro as I do not have appropriate permissions.
Changes for invalidation lambda include other environment but I suspect that is due to s3 object changing.
<details>
<summary>output of …
> Tidy iiif lower environments

- accounts/describe_access_key.py
"The key has been deactivated" was the answer to "why isn't this key working" today.
> Check whether an IAM key is active in the "lookup key" script

- cloudfront/api.wellcomecollection.org/send_slack_alert_for_5xx_errors.js
Extending the duration in the logging link sent as part of the slack alert make it easier to see the context of an error.
id                             = "send_slack_alert_for_5xx_errors"
~ last_modified                  = "2023-04-16T18:37:49.000+0000" -> (known after apply)
~ source_code_hash               = "L5tGrKkuQThjeB7gsceC+vX4calKT6rm2pN5xiekamI=" -> "R0JbOWqqXdQfv9GCd+siIU3ZhmlIJp3uByGwNSj5naU="
}
Plan: 0 to add, 1 to change, 0 to destroy.
> expand timeframe in cloudfront kibana link

- cloudfront/iiif.wellcomecollection.org/terraform/.terraform.lock.hcl
- cloudfront/iiif.wellcomecollection.org/terraform/cf_behaviours.tf
- cloudfront/iiif.wellcomecollection.org/terraform/cf_origins.tf
- cloudfront/iiif.wellcomecollection.org/terraform/s3.tf
- critical/lambda_logging.tf
Added a new behaviour/origin for IIIF Auth v2 (test + staging env only to verify setup).
New origins are `dlcs.io/auth/v2/probe/*` and `dlcs.io/auth/v2/*`.
There was already a `dlcs_auth` behaviour which handled `/auth/*` paths (for IIIF auth v1). 
I added the new `dlcs_auth_2` / `/auth/v2/*` behaviour as a lower precedence to ensure it is evaluated before ^. This has resulted in some behaviours being re-ordered and the `terraform plan` being pretty large.
I initially included `terraform plan` output but it was too large and I received an error: 
> Pull request creation failed. Validation failed: Body is too long (maximum is 65536 characters)
> Update test/staging IIIF Cloudfront for IIIF Auth2

- cloudfront/iiif.wellcomecollection.org/tests/rewrite_tests.py
This makes the tests stop exploding, but perhaps they should be removed altogether
> Stop unexpected error in IIIF redirect tests

- cloudfront/iiif.wellcomecollection.org/edge-lambda/src/dlcs_path_rewrite.test.ts
- cloudfront/iiif.wellcomecollection.org/edge-lambda/src/dlcs_path_rewrite.ts
- cloudfront/iiif.wellcomecollection.org/terraform/cf_origins.tf
This PR extends changes made via #402.
After testing deployed DLCS it became apparent that the CloudFront origin paths needed to be altered.
In addition to this the lambda@edge function needed some slight alterations to allow us to handle incoming paths correctly. It looks like the same lambda is used for all envs, this change should be safe to apply as there will be no prod requests that match `/^\/auth\/v2\/.+/` as this is a new path.
> Further updates to iiif-stage and iiif-test CloudFront config for iiif-auth2

- cloudfront/iiif.wellcomecollection.org/terraform/cf_behaviours.tf
Seeing odd results when testing clickthrough auth as some requests are served as cloudfront hits.
> Don't cache any auth2 paths in CF

- cloudfront/iiif.wellcomecollection.org/terraform/cf_behaviours.tf
- cloudfront/iiif.wellcomecollection.org/terraform/cf_origins.tf
- cloudfront/iiif.wellcomecollection.org/terraform/locals.tf
#402, #404 and #406 updated Cloudfront and associated lambda@edge for handling iiif auth v2 paths. This PR makes the same changes for production environment. Summary:
* Update lambda@edge used in prod environment to latest version
* Add 2 new behaviours, mimicking those added to test + stage
* Add 2 new origins, again mimicking those added in test + stage (initially added in #402 then updated in #404).
> Generated diff too large
> Add iiif-auth-2 paths to prod + update lambda@edge version

- critical/.terraform.lock.hcl
- critical/elastic_logging_cluster.tf
- critical/lambda_logging.tf
- critical/provider.tf
We see out-of-storage warnings for the logging cluster sometimes, and usually I go and delete some old APM trace indices to fix them. This is a bad idea.
This PR makes the computer delete the indices for us - the exact configuration will probably require tweaking in future; I've been quite conservative at first so as not to throw away too much potentially useful data. It's done as documented here https://www.elastic.co/guide/en/apm/guide/current/ilm-how-to.html
The component template things already exist (they're managed by Fleet) and I think I will have to import them when I come to apply this.
```
+ resource "elasticstack_elasticsearch_component_template" "apm_traces_managed_custom" {
+ id   = (known after apply)
+ name = "traces-apm@custom"
+ template {
+ settings = jsonencode(
{
+ …
```
> Lifecycle management for APM traces

- images/dockerfiles/nginx/frontend.nginx.conf
- images/dockerfiles/nginx/frontend_identity.nginx.conf
- images/dockerfiles/publish_nginx_images.sh
This change removes the healthcheck endpoints from the frontend and frontend_identity docker images so these can now reach the app containers which serve there own healthchecks.
We also update the publish scripts to be a bit neater and use functions.
See https://github.com/wellcomecollection/wellcomecollection.org/issues/10545 for the motivation for this change.
In order to use this change, we should:
- `760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/nginx_frontend:b809c6ef4363ff0cbac8da7ff5e80d865cfcd008`
- `760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/nginx_frontend_identity:b809c6ef4363ff0cbac8da7ff5e80d865cfcd008`
- https://github.com/wellcomecollection/terraform-aws-ecs-service/pull/52
- https://github.com/wellcomecollection/wellcomecollection.org/pull/1061 …
> Remove healthcheck endpoints from nginx configuration for frontend

- images/dockerfiles/awstoe/Dockerfile
- images/dockerfiles/awstoe/README.md
- images/dockerfiles/awstoe/components/.gitkeep
- images/dockerfiles/awstoe/components/hello-world.yml
- images/dockerfiles/awstoe/docker-compose.yml
- images/dockerfiles/awstoe/run.sh
- images/terraform/.terraform.lock.hcl
- images/terraform/image-builder.tf
- images/terraform/image-builder/components/crowdstrike-agent.yml
- images/terraform/image-builder/components/qualys-agent.yml
- images/terraform/image-builder/distribution_configuration.tf
- images/terraform/image-builder/iam_role.tf
- images/terraform/image-builder/image.tf
- images/terraform/image-builder/image_pipeline.tf
- images/terraform/image-builder/image_recipe.tf
- images/terraform/image-builder/infrastructure_configuration.tf
- images/terraform/image-builder/security_group.tf
- images/terraform/image-builder/variables.tf
- images/terraform/locals.tf
- images/terraform/terraform.tf
This change attempts to provision an AWS image-builder pipeline to install necessary agents on our EC2 instances as part of a base AMI.
See: https://github.com/wellcomecollection/platform-infrastructure/issues/410
Borrows heavily from: https://github.com/aws-ia/terraform-aws-ec2-image-builder
Run the image builder pipeline by doing `terraform apply`, an image should be successfully built and distributed.
Our EC2 instances can easily and repeatably be kept up to date with security / monitoring requirements as well as ensuring we reduce our security risk by keeping our images up to date.
> Add image-builder for required base images (monitoring agents)

- critical/elastic_logging_cluster.tf
This change allows indices rolled over hot to warm to be kept for 1 day, and then deleted straight away. Currently the hot phase rollover rules keep the apm_traces indices (these tend to be the largest) around for 30 days or until they reach 50GB (total disk size at present is 250GB).
The expected process is:
- After either 30 days, or the hot index reaches 30gb it is rolled over to the warm phase
- After another day the deletion can occur immediately, we've specified the min_age as 1 day (after rollover).
We reduce the max size of the hot index from 50gb to 30gb to allow expected space for 2 hot indices, the delete `min_age` providing us with a buffer before deletion.
For context see:
- https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-index-lifecycle.html#ilm-phase-tran …
> Remove min-age on deletion phase of apm_traces ILM policies

- monitoring/slack_alerts/auth0_log_stream_alert/src/auth0_log_stream_alert.py
The alert description filter for "Missing required parameter: response_type" was missing the underscore, this adds it.
See the description being output in Slack:
```console
module.auth0_log_stream_alerts.module.auth0_log_stream_alerts.module.lambda.aws_lambda_function.lambda_function will be updated in-place
id                             = "identity_auth0_log_stream_alerts"
~ last_modified                  = "2024-02-19T09:47:52.000+0000" -> (known after apply)
~ source_code_hash               = "MXCUFp/ZwKdgUMRnlvR0oQheEaFzTpJfyRiAunJX7cw=" -> "dBIBz3ywIXiFJhxefEB++XIV7XOXTTRif4I+Je4Bu5A="
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
> [!NOTE]
> This change is applied.
> Update the alert description filter

- cloudfront/api.wellcomecollection.org/send_slack_alert_for_5xx_errors.js
We've seen [errors](https://wellcome.slack.com/archives/CQ720BG02/p1720597318517099) in this lambda, which should be fixed by this addition of optional chaining in case `query` is `null`
```
id                             = "send_slack_alert_for_5xx_errors"
~ last_modified                  = "2024-05-03T08:25:21.000+0000" -> (known after apply)
~ source_code_hash               = "Oq9I+XxfJXbNIs2Af3laOK5mksm6C/gzV4zRdDFQyQ4=" -> "Muyhd941OhW1yIHHSbtKNyrHywvymTj0LntBt9NxVsE="
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
> optional chaining in case query is not defined/null

- images/dockerfiles/sbt_wrapper/Dockerfile
- images/dockerfiles/sbt_wrapper/install_sbt.sh
This change moves from using an alpine os version of sbt-wrapper, to using the slightly larger dependencies included ubuntu version.
We've seen places where tests fail because there are missing dependencies. This change resolves that issue at the cost of increased data transfer in CI.
See: https://buildkite.com/wellcomecollection/storage-service/builds/1748#018ee239-8e8c-4f39-b46a-7e8009748236/183-550
The new container image reports:
```
root@61480c352c5a:/repo# uname -a
Linux 61480c352c5a 6.6.16-linuxkit #1 SMP Fri Feb 16 11:54:02 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
root@61480c352c5a:/repo# cat /etc/
Display all 107 possibilities? (y or n)
root@61480c352c5a:/repo# cat /etc/o
opt/        os-release
root@61480c352c5a:/repo# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS" …
```
> Remove alpine from sbt_wrapper

- cloudfront/api.wellcomecollection.org/.terraform.lock.hcl
- critical/.terraform.lock.hcl
- critical/lambda_logging.tf
- critical/locals.tf
- critical/provider.tf
This adds the log forwarder SSM parameter to the digitisation account and updates kinesis in the platform account so that digitisation Lambdas can forward logs to our common logging platform
```
+ resource "aws_ssm_parameter" "log_destination_arn_digitisation" {
+ arn            = (known after apply)
+ data_type      = (known after apply)
+ id             = (known after apply)
+ insecure_value = (known after apply)
+ key_id         = (known after apply)
+ name           = "/logging/forwarder/destination_arn"
+ tags_all       = {
+ "TerraformConfigurationURL" = "https://github.com/wellcomecollection/platform-infrastructure/tree/main/critical"
}
+ tier           = (known after apply)
+ type           = "String"
+ value          = (sensitive value)
+ version        = (known after apply)
}
~ …
```
> Digitisation lambda logging

- critical/elastic_logging_cluster.tf
This modifies the `delete` policy on APM trace indices to make sure they get deleted 1 day after rollover. See [this thread](https://wellcome.slack.com/archives/C02ANCYL90E/p1721917048277189) for more info
```tf
~ resource "elasticstack_elasticsearch_index_lifecycle" "apm_traces" {
id            = "J6V5gvONTve393_OJiiJnA/weco-traces-apm"
name          = "weco-traces-apm"
~ delete {
+ delete {
+ delete_searchable_snapshot = true
}
}
}
~ resource "elasticstack_elasticsearch_index_lifecycle" "apm_traces_rum" {
id            = "J6V5gvONTve393_OJiiJnA/weco-traces-apm-rum"
name          = "weco-traces-apm-rum"
~ delete {
+ delete {
+ delete_searchable_snapshot = true
}
}
}
Plan: 0 to add, 2 to change, 0 to destroy.
```
> Fix logging cluster ILM policies

- cloudfront/api.wellcomecollection.org/.terraform.lock.hcl
- cloudfront/api.wellcomecollection.org/lambda/lambda_function.tf
- cloudfront/api.wellcomecollection.org/send_slack_alert_for_5xx_errors.tf
Memory increased from 128 (default var) to 256 as per #443 
```
Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
~ update in-place
-/+ destroy and then create replacement
-/+ resource "aws_iam_role_policy" "allow_s3_read" {
~ id          = "lambda_send_slack_alert_for_5xx_errors:terraform-20230321122311397500000001" -> (known after apply)
~ name        = "terraform-20230321122311397500000001" -> (known after apply)
- name_prefix = "terraform-" -> null # forces replacement
}
id                             = "send_slack_alert_for_5xx_errors"
~ last_modified                  = …
```
> increased memory from 128 (default) to 256

- cloudfront/iiif.wellcomecollection.org/terraform/waf/main.tf
This change removes the request body size rules in the IIIF WAF to allow large POST requests required for the IIIF dashboard to succeed. It is probably largely non-impactful as we don't see this as an issue via the WAF at the moment.
See: https://wellcome.slack.com/archives/CBT40CMKQ/p1723718811584909
> Remove request body restrictions from IIIF API WAF

- cloudfront/wellcomecollection.org/terraform/main.tf
> [!Note]
> This terraform change change is applied.
For https://github.com/wellcomecollection/platform/issues/5814
Adds a DNS record used for validation for Sectigo a certificate validation platform used by NCW (Cloud Team).
```
+ resource "aws_route53_record" "subdomains" {
+ allow_overwrite = (known after apply)
+ fqdn            = (known after apply)
+ id              = (known after apply)
+ name            = "_0dc4e7168ed7814510307bb24b6f7418.wellcomecollection.org"
+ records         = [
+ "699a0e70174c47ab5faaf2993303e2ad.962cb5fa70ca907c6d976adbedfe809a.sectigo.com",
]
+ ttl             = 300
+ type            = "CNAME"
+ zone_id         = "Z0902614YH73JBCZG1MA"
}
Plan: 1 to add, 0 to change, 0 to destroy.
```
Happy NCW team with no red …
> Add Sectigo CNAME record for wellcomecollection.org

- cloudfront/invalidation/lambda/deploy.js
- cloudfront/invalidation/lambda/package.json
- cloudfront/invalidation/lambda/yarn.lock
Following https://github.com/wellcomecollection/platform-infrastructure/pull/452
The deploy script was missed, that used the defunct and removed aws-sdk 
Using the v3 S3 client and credential provider instead
`yarn install`
Change `s3Key` to a dummy location
`node deploy` 
The build pipeline doesn't fail at the deploy step
See linked PR
> deploy script uses sdk v3

- cloudfront/iiif.wellcomecollection.org/edge-lambda/Dockerfile
- cloudfront/iiif.wellcomecollection.org/edge-lambda/deploy.js
- cloudfront/iiif.wellcomecollection.org/edge-lambda/package.json
- cloudfront/iiif.wellcomecollection.org/edge-lambda/src/dlcs_path_rewrite.ts
- cloudfront/iiif.wellcomecollection.org/edge-lambda/yarn.lock
- cloudfront/iiif.wellcomecollection.org/terraform/lambda_dlcs_path_rewrite.tf
- cloudfront/iiif.wellcomecollection.org/terraform/locals.tf
Part of https://github.com/wellcomecollection/platform/issues/5837
???
The deploy script works alright for the invalidation lambdas
`dlcs_path_rewrite` is on node20 and images are being served
We can't get any dlcs images on weco.org 😱
> up runtime and update deploy script for sdk v3

- critical/elastic_logging_cluster.tf
- critical/elastic_privatelink.tf
- critical/outputs.tf
For https://github.com/wellcomecollection/catalogue-graph/pull/21
This change adds a VPCE for developer vpc to allow communication with Elastic Cloud, so ECS tasks can send logs.
Log visibility!
This allows tasks running in the developer VPC to talk to elasticsearch over a privatelink endpoint, but they can at the moment also talk over the public internet, so risk is minimal.
> Add VPCE for developer vpc to allow communication with Elastic Cloud

- images/dockerfiles/nginx/frontend.nginx.conf
Part of https://github.com/wellcomecollection/platform/issues/5919
This change in intended to improve connection handling performance of our front-end ECS tasks. We believe this may improve handling of large volumes of bot requests we have been seeing recently.
- [`worker_processes`](https://nginx.org/en/docs/ngx_core_module.html#worker_processes): Changed from `1` to `auto` in order to dyanimcally increase the number of worker processes available to deal with requests. In production there is > 1 processor available so it makes sense to update this value.
- [ `worker_connections`](https://nginx.org/en/docs/ngx_core_module.html#worker_connections): Changed from `1024` to `2048` in order to handle more connections before we start refusing them. I suspect this is part of the issue with …
> Update nginx frontend configuration

- cloudfront/iiif.wellcomecollection.org/edge-lambda/package.json
- cloudfront/iiif.wellcomecollection.org/edge-lambda/yarn.lock
- cloudfront/invalidation/lambda/package.json
- cloudfront/invalidation/lambda/yarn.lock
Update npm packages for the `cloudfront/iiif.wellcomecollection.org/edge-lambda` and `cloudfront/invalidation/lambda` Lambda functions. 
Automated testing should be sufficient. 
The change only involves updating the `jest` package to the latest version, and allowing minor version updates of the `@aws-sdk/client-s3` package.
> Update cloudfront invalidation lambda dependencies

- cloudfront/iiif.wellcomecollection.org/terraform/waf/main.tf
- cloudfront/invalidation/lambda/package.json
- cloudfront/invalidation/lambda/yarn.lock
- cloudfront/invalidation/terraform/terraform.tf
> [!NOTE]
> I don't have appropriate access to `terraform plan` these changes so please let me know if there are errors.
Adds rate-limiting to iiif.weco.org WAF rules. Based on those provided by Agnes from https://github.com/wellcomecollection/wellcomecollection.org/blob/main/cache/modules/wc_org_cloudfront/waf.tf
Approach is:
* Blanket limit set to for endpoints. Except:
* Restrictive rate on `/presentation/collections*` as we previously encountered issues with high volume of requests to this endpoint.
* More lenient rate on `/images*` and `/thumbs*` as these expect to high volume of traffic.
Apply to test / stage (ie non-prod environment) initially and make a flood of requests from single endpoint. Validate 429 is returned.
Requests to `/presentation/collections*` have been disabled, …
> Add rate-limiting to iiif.weco waf
